[package]
name = "patlang_runtime"
version = "0.1.0"
edition = "2024"

[lib]
name = "patlang_runtime"
path = "src/lib.rs"

[features]
default = []
parser = []

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hyper = { version = "0.14", features = ["full"] }
serde_yaml = "0.9"
uuid = { version = "1.17.0", features = ["v4"] }
num-bigint = "0.4"

[dev-dependencies]
cargo-tarpaulin = "0.27"

[[bin]]
name = "pat"
path = "src/main.rs"

[alias]
cov = "llvm-cov --workspace --lcov --output-path lcov.info"
cov-html = "llvm-cov --workspace --html --open"