use super::types::*;

pub struct RustCodegen;

impl RustCodegen {
    pub fn new() -> Self { Self }

    // Emit a standalone Rust program that embeds the IR as a multi-function Program
    pub fn emit_rust(&self, program: &Program) -> String {
        let mut out = String::new();
    out.push_str(r#"// Auto-generated by patlang IR→Rust codegen (Stage 0)
#![allow(dead_code, unused_imports, unused_variables, unused_mut)]
// Standalone runtime + embedded program

use std::collections::HashMap;
use std::cell::RefCell;

thread_local! {
    static OBJECTS: RefCell<HashMap<String, HashMap<String, Value>>> = RefCell::new(HashMap::new());
    static FACTS: RefCell<HashMap<String, Vec<(String, String)>>> = RefCell::new(HashMap::new());
    static GOALS: RefCell<Vec<(String, Vec<String>)>> = RefCell::new(Vec::new());
    static TYPE_RULES: RefCell<HashMap<(String, usize), String>> = RefCell::new(HashMap::new());
}

fn obj_get(name: &str, prop: &str) -> Option<Value> {
    OBJECTS.with(|o| {
        let b = o.borrow();
        b.get(name).and_then(|m| m.get(prop)).cloned()
    })
}

fn obj_set(name: &str, prop: &str, val: Value) {
    OBJECTS.with(|o| {
        let mut b = o.borrow_mut();
        let m = b.entry(name.to_string()).or_insert_with(HashMap::new);
        m.insert(prop.to_string(), val);
    });
}

fn ensure_obj(name: &str, class: &str) {
    obj_set(name, "type", Value::String(class.to_string()));
    obj_set(name, "name", Value::String(name.to_string()));
}

#[derive(Clone, Debug, PartialEq)]
enum Value {
    Unit,
    Bool(bool),
    Number(f64),
    String(String),
    List(Vec<Value>),
    Object(HashMap<String, Value>),
}

impl Value {
    fn as_number(&self) -> Result<f64, String> {
        match self {
            Value::Number(n) => Ok(*n),
            Value::Unit => Ok(0.0),
            _ => Err("expected number".into()),
        }
    }
    fn as_bool(&self) -> Result<bool, String> {
        match self {
            Value::Bool(b) => Ok(*b),
            Value::Unit => Ok(false),
            Value::Number(n) => Ok(*n != 0.0),
            Value::String(s) => Ok(!s.is_empty()),
            Value::List(xs) => Ok(!xs.is_empty()),
            Value::Object(map) => Ok(!map.is_empty()),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
enum BinOpKind { Add, Sub, Mul, Div, Mod, Eq, Ne, Lt, Le, Gt, Ge, And, Or }
#[derive(Clone, Debug, PartialEq)]
enum UnOpKind { Neg, Not }

#[derive(Clone, Debug, PartialEq)]
enum Instr {
    Const(Value),
    LoadLocal(String),
    StoreLocal(String),
    BinOp(BinOpKind),
    UnOp(UnOpKind),
    Jump(usize),
    JumpIfFalse(usize),
    CallHost(String, usize),
    Call(String, usize),
    BuildList(usize),
    Return,
}

struct Host;

impl Host {
    fn call(name: &str, args: &[Value]) -> Result<Value, String> {
        match name {
            "infer_type_for" => {
                // args: pred, index, class
                if args.len() != 3 { return Ok(Value::Unit); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let idx = match &args[1] { Value::Number(n) => *n as usize, Value::String(s) => s.parse::<usize>().unwrap_or(0), _ => 0 };
                let class = match &args[2] { Value::String(s) => s.clone(), _ => String::new() };
                TYPE_RULES.with(|tr| { tr.borrow_mut().insert((pred, idx), class); });
                Ok(Value::Unit)
            }
            "fact" => {
                if args.len() != 3 { return Ok(Value::Unit); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let a = to_s(args.get(1).unwrap_or(&Value::Unit));
                let b = to_s(args.get(2).unwrap_or(&Value::Unit));
                FACTS.with(|f| {
                    let mut m = f.borrow_mut();
                    m.entry(pred).or_insert_with(Vec::new).push((a, b));
                });
                Ok(Value::Unit)
            }
            "goal" => {
                if args.is_empty() { return Ok(Value::Unit); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let mut items: Vec<String> = Vec::new();
                for a in &args[1..] { items.push(to_s(a)); }
                GOALS.with(|g| { g.borrow_mut().push((pred, items)); });
                Ok(Value::Unit)
            }
            "query" => {
                if args.len() != 3 { return Ok(Value::Number(0.0)); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let a = to_s(args.get(1).unwrap_or(&Value::Unit));
                let mut count = 0usize;
                let mut bs: Vec<String> = Vec::new();
                FACTS.with(|f| {
                    if let Some(v) = f.borrow().get(&pred) {
                        for (x, b) in v.iter() {
                            if x == &a { count += 1; bs.push(b.clone()); }
                        }
                    }
                });
                // Apply simple type inference rules recorded
                TYPE_RULES.with(|tr| {
                    let rules = tr.borrow();
                    if let Some(class0) = rules.get(&(pred.clone(), 0usize)) { ensure_obj(&a, class0); }
                    if let Some(class1) = rules.get(&(pred.clone(), 1usize)) {
                        for b in bs.iter() { ensure_obj(b, class1); }
                    }
                });
                Ok(Value::Number(count as f64))
            }
            "new" => {
                if args.len() != 2 { return Ok(Value::Unit); }
                let class = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let name = match &args[1] { Value::String(s) => s.clone(), _ => String::new() };
                if !name.is_empty() { ensure_obj(&name, &class); }
                Ok(Value::String(name))
            }
            "print" => { if let Some(x) = args.get(0) { println!("{}", display_value(x)); } Ok(Value::Unit) },
            "add" => host_bin_num(args, |a,b| a+b),
            "multiply" => host_bin_num(args, |a,b| a*b),
            "subtract" => host_bin_num(args, |a,b| a-b),
            "max" => host_bin_num(args, |a,b| a.max(b)),
            "min" => host_bin_num(args, |a,b| a.min(b)),
            "calculate" => Ok(Value::Number(0.0)),
            "calculate_result" => Ok(Value::Number(0.0)),
            "get_value" => Ok(Value::Number(0.0)),
            "process" => Ok(Value::Bool(true)),
            "validate" => Ok(Value::Bool(true)),
            "len" => {
                let v = args.get(0).cloned().unwrap_or(Value::Unit);
                let n = match v {
                    Value::String(s) => s.chars().count() as f64,
                    Value::List(xs) => xs.len() as f64,
                    Value::Object(m) => m.len() as f64,
                    Value::Unit => 0.0,
                    _ => 0.0,
                };
                Ok(Value::Number(n))
            }
            "get" => {
                if args.len() != 2 { return Err("expected 2 args".into()); }
                let key = match &args[1] { Value::String(s) => s.clone(), _ => return Err("expected string key".into()) };
                match &args[0] {
                    Value::String(name) => Ok(obj_get(name, &key).unwrap_or(Value::Unit)),
                    Value::Object(map) => Ok(map.get(&key).cloned().unwrap_or(Value::Unit)),
                    _ => Ok(Value::Unit),
                }
            }
            "send" => {
                if args.len() < 2 { return Ok(Value::Unit); }
                let recv = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let method = match &args[1] { Value::String(s) => s.clone(), _ => String::new() };
                let rest = &args[2..];
                match method.as_str() {
                    "set" => {
                        if rest.len() != 2 { return Ok(Value::Unit); }
                        let prop = match &rest[0] { Value::String(s) => s.clone(), _ => String::new() };
                        let val = rest[1].clone();
                        if !recv.is_empty() && !prop.is_empty() { obj_set(&recv, &prop, val); }
                        Ok(Value::Unit)
                    }
                    "infer_is_adult" => {
                        // reads age, sets is_adult when >= 18
                        if let Some(Value::Number(age)) = obj_get(&recv, "age") {
                            if age >= 18.0 { obj_set(&recv, "is_adult", Value::Bool(true)); return Ok(Value::Bool(true)); }
                        } else if let Some(Value::String(s)) = obj_get(&recv, "age") {
                            if s.parse::<f64>().unwrap_or(0.0) >= 18.0 { obj_set(&recv, "is_adult", Value::Bool(true)); return Ok(Value::Bool(true)); }
                        }
                        Ok(Value::Bool(false))
                    }
                    "infer_relations" => {
                        // if exists fact("parent", X, recv) then set has_parent true
                        let mut has = false;
                        FACTS.with(|f| {
                            if let Some(v) = f.borrow().get("parent") {
                                has = v.iter().any(|(_, child)| child == &recv);
                            }
                        });
                        if has { obj_set(&recv, "has_parent", Value::Bool(true)); return Ok(Value::Bool(true)); }
                        Ok(Value::Bool(false))
                    }
                    _ => Ok(Value::Unit),
                }
            }
            other => Err(format!("host fn '{}' not found", other)),
        }
    }
}

fn host_bin_num(args: &[Value], f: fn(f64,f64)->f64) -> Result<Value, String> {
    let a = args.get(0).ok_or("expected 2 args")?;
    let b = args.get(1).ok_or("expected 2 args")?;
    let an = a.as_number()?; let bn = b.as_number()?;
    Ok(Value::Number(f(an,bn)))
}

fn display_value(v: &Value) -> String {
    match v {
        Value::Unit => String::new(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => if n.fract()==0.0 { format!("{}", *n as i64) } else { n.to_string() },
        Value::String(s) => s.clone(),
        Value::List(xs) => {
            let parts: Vec<String> = xs.iter().map(|x| display_value(x)).collect();
            format!("[{}]", parts.join(", "))
        }
        Value::Object(map) => {
            let mut kvs: Vec<String> = map.iter().map(|(k,v)| format!("{}: {}", k, display_value(v))).collect();
            kvs.sort();
            format!("{{{}}}", kvs.join(", "))
        }
    }
}

#[derive(Clone)]
struct Function { name: String, params: Vec<String>, body: Vec<Instr> }

struct Program { functions: HashMap<String, Function>, entry: String }

fn run(program: &Program) -> Result<Value,String> {
    let entry = program.functions.get(&program.entry).ok_or("entry not found")?;
    run_function(program, entry, &[])
}

fn run_function(program: &Program, func: &Function, args: &[Value]) -> Result<Value,String> {
    let mut pc: usize = 0;
    let mut stack: Vec<Value> = Vec::new();
    let mut locals: HashMap<String, Value> = HashMap::new();
    // bind params
    for (i, p) in func.params.iter().enumerate() { if let Some(v) = args.get(i) { locals.insert(p.clone(), v.clone()); } }
    while pc < func.body.len() {
        match &func.body[pc] {
            Instr::Const(v) => stack.push(v.clone()),
            Instr::LoadLocal(n) => stack.push(locals.get(n).cloned().unwrap_or(Value::Unit)),
            Instr::StoreLocal(n) => { let v = stack.pop().ok_or("stack underflow")?; locals.insert(n.clone(), v); },
            Instr::UnOp(k) => {
                let a = stack.pop().ok_or("stack underflow")?;
                let r = match k { UnOpKind::Neg => Value::Number(-a.as_number()?), UnOpKind::Not => Value::Bool(!a.as_bool()?) };
                stack.push(r);
            }
            Instr::BinOp(k) => {
                use BinOpKind::*;
                let b = stack.pop().ok_or("stack underflow")?;
                let a = stack.pop().ok_or("stack underflow")?;
                let r = match k {
                    Add => add(&a,&b)?, Sub => sub(&a,&b)?, Mul => mul(&a,&b)?, Div => div(&a,&b)?, Mod => modu(&a,&b)?,
                    Eq|Ne|Lt|Le|Gt|Ge => cmp(k, &a, &b)?,
                    And => Value::Bool(a.as_bool()? && b.as_bool()?),
                    Or => Value::Bool(a.as_bool()? || b.as_bool()?),
                };
                stack.push(r);
            }
            Instr::Jump(t) => { pc = *t; continue; }
            Instr::JumpIfFalse(t) => { let c = stack.pop().ok_or("stack underflow")?; if !c.as_bool()? { pc = *t; continue; } }
            Instr::CallHost(n, argc) => {
                let argc = *argc; if stack.len() < argc { return Err("stack underflow".into()); }
                let args_index = stack.len() - argc; let args: Vec<Value> = stack.drain(args_index..).collect();
                let r = Host::call(n, &args)?; stack.push(r);
            }
            Instr::Call(n, argc) => {
                let argc = *argc; if stack.len() < argc { return Err("stack underflow".into()); }
                let args_index = stack.len() - argc; let args: Vec<Value> = stack.drain(args_index..).collect();
                let callee = program.functions.get(n).ok_or_else(|| format!("function '{}' not found", n))?;
                let r = run_function(program, callee, &args)?; stack.push(r);
            }
            Instr::BuildList(n) => { let n=*n; if stack.len()<n {return Err("stack underflow".into());} let start=stack.len()-n; let items: Vec<Value>=stack.drain(start..).collect(); stack.push(Value::List(items)); }
            Instr::Return => { return Ok(stack.pop().unwrap_or(Value::Unit)); }
        }
        pc += 1;
    }
    Ok(stack.pop().unwrap_or(Value::Unit))
}

fn add(a:&Value,b:&Value)->Result<Value,String>{
    match (a,b) {
        (Value::String(sa), _) => Ok(Value::String(format!("{}{}", sa, to_s(b)))),
        (_, Value::String(sb)) => Ok(Value::String(format!("{}{}", to_s(a), sb))),
        _ => Ok(Value::Number(a.as_number()? + b.as_number()?)),
    }
}
fn sub(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? - b.as_number()?)) }
fn mul(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? * b.as_number()?)) }
fn div(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? / b.as_number()?)) }
fn modu(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? % b.as_number()?)) }
fn cmp(k:&BinOpKind,a:&Value,b:&Value)->Result<Value,String>{
    let (an,bn)=(a.as_number()?, b.as_number()?);
    use BinOpKind::*;
    let res = match k { Eq=>an==bn, Ne=>an!=bn, Lt=>an<bn, Le=>an<=bn, Gt=>an>bn, Ge=>an>=bn, _=>false };
    Ok(Value::Bool(res))
}
fn to_s(v:&Value)->String{ match v { Value::Unit=>String::new(), Value::Bool(b)=>b.to_string(), Value::Number(n)=> if n.fract()==0.0 {format!("{}",*n as i64)} else {n.to_string()}, Value::String(s)=>s.clone(), Value::List(xs)=>{ let parts:Vec<String>=xs.iter().map(|x|to_s(x)).collect(); format!("[{}]", parts.join(", ")) }, Value::Object(map)=>{ let mut kvs:Vec<String>=map.iter().map(|(k,v)| format!("{}: {}",k,to_s(v))).collect(); kvs.sort(); format!("{{{}}}", kvs.join(", ")) } } }

fn main(){
    let program = build_program();
    match run(&program) { Ok(v) => println!("{}", display_value(&v)), Err(e) => { eprintln!("IR runtime error: {}", e); std::process::exit(1); } }
}

"#);

        // program builder: emit all functions with params and bodies
        out.push_str("fn build_program() -> Program {\n    let mut functions: HashMap<String, Function> = HashMap::new();\n");
        // Emit each function body and insert into map
        for (name, func) in program.functions.iter() {
            out.push_str(&format!("    // function {}\n", name));
            out.push_str("    let mut body: Vec<Instr> = Vec::new();\n");
            for instr in &func.body {
                out.push_str("    body.push(");
                self.emit_instr(instr, &mut out);
                out.push_str(");\n");
            }
            // emit params vec
            out.push_str("    let params: Vec<String> = vec![");
            for (i, p) in func.params.iter().enumerate() {
                if i>0 { out.push_str(", "); }
                out.push_str(&format!("\"{}\".to_string()", rust_str(p)));
            }
            out.push_str("];\n");
            out.push_str(&format!(
                "    functions.insert(\"{}\".to_string(), Function {{ name: \"{}\".to_string(), params, body }});\n",
                rust_str(name), rust_str(name)
            ));
        }
        out.push_str(&format!("    Program {{ functions, entry: \"{}\".to_string() }}\n}}\n", rust_str(&program.entry)));

        out
    }

    fn emit_instr(&self, instr: &Instr, out: &mut String) {
        match instr {
            Instr::Const(v) => {
                out.push_str("Instr::Const(");
                self.emit_value(v, out);
                out.push(')');
            }
            Instr::LoadLocal(n) => {
                out.push_str(&format!("Instr::LoadLocal(\"{}\".to_string())", rust_str(n)));
            }
            Instr::StoreLocal(n) => {
                out.push_str(&format!("Instr::StoreLocal(\"{}\".to_string())", rust_str(n)));
            }
            Instr::BinOp(k) => {
                out.push_str("Instr::BinOp(");
                self.emit_binop(k, out);
                out.push(')');
            }
            Instr::UnOp(k) => {
                out.push_str("Instr::UnOp(");
                match k { UnOpKind::Neg => out.push_str("UnOpKind::Neg"), UnOpKind::Not => out.push_str("UnOpKind::Not") }
                out.push(')');
            }
            Instr::Jump(t) => out.push_str(&format!("Instr::Jump({})", t)),
            Instr::JumpIfFalse(t) => out.push_str(&format!("Instr::JumpIfFalse({})", t)),
            Instr::CallHost(n, argc) => {
                out.push_str(&format!("Instr::CallHost(\"{}\".to_string(), {})", rust_str(n), argc));
            }
            Instr::Call(n, argc) => {
                out.push_str(&format!("Instr::Call(\"{}\".to_string(), {})", rust_str(n), argc));
            }
            Instr::BuildList(n) => out.push_str(&format!("Instr::BuildList({})", n)),
            Instr::Return => out.push_str("Instr::Return"),
        }
    }

    fn emit_binop(&self, k: &BinOpKind, out: &mut String) {
        use BinOpKind::*;
        let s = match k { Add=>"Add", Sub=>"Sub", Mul=>"Mul", Div=>"Div", Mod=>"Mod", Eq=>"Eq", Ne=>"Ne", Lt=>"Lt", Le=>"Le", Gt=>"Gt", Ge=>"Ge", And=>"And", Or=>"Or" };
        out.push_str(&format!("BinOpKind::{}", s));
    }

    fn emit_value(&self, v: &Value, out: &mut String) {
        match v {
            Value::Unit => out.push_str("Value::Unit"),
            Value::Bool(b) => out.push_str(&format!("Value::Bool({})", b)),
            Value::Number(n) => {
                if n.fract() == 0.0 {
                    out.push_str(&format!("Value::Number({}.0)", *n as i64));
                } else {
                    out.push_str(&format!("Value::Number({})", n));
                }
            }
            Value::String(s) => out.push_str(&format!("Value::String(\"{}\".to_string())", rust_str(s))),
            Value::List(items) => {
                out.push_str("Value::List(vec![");
                for (i, it) in items.iter().enumerate() { if i>0 { out.push_str(", "); } self.emit_value(it, out); }
                out.push_str("])");
            }
            Value::Object(map) => {
                if map.is_empty() {
                    out.push_str("Value::Object(HashMap::new())");
                } else {
                    out.push_str("{ let mut m: HashMap<String, Value> = HashMap::new(); ");
                    for (k, v) in map.iter() {
                        out.push_str(&format!("m.insert(\"{}\".to_string(), ", rust_str(k)));
                        self.emit_value(v, out);
                        out.push_str("); ");
                    }
                    out.push_str("Value::Object(m) }");
                }
            }
            Value::HostFunction(_) => { out.push_str("Value::Unit"); }
        }
    }
}

fn rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
