// Auto-generated by patlang IR→Rust codegen (Stage 0)
#![allow(dead_code, unused_imports, unused_variables, unused_mut)]
// Standalone runtime + embedded program

use std::collections::HashMap;
use std::cell::RefCell;

thread_local! {
    static OBJECTS: RefCell<HashMap<String, HashMap<String, Value>>> = RefCell::new(HashMap::new());
    static FACTS: RefCell<HashMap<String, Vec<(String, String)>>> = RefCell::new(HashMap::new());
    static GOALS: RefCell<Vec<(String, Vec<String>)>> = RefCell::new(Vec::new());
    static TYPE_RULES: RefCell<HashMap<(String, usize), String>> = RefCell::new(HashMap::new());
    static EVENT_HANDLERS: RefCell<HashMap<String, Vec<String>>> = RefCell::new(HashMap::new());
}

fn obj_get(name: &str, prop: &str) -> Option<Value> {
    OBJECTS.with(|o| {
        let b = o.borrow();
        b.get(name).and_then(|m| m.get(prop)).cloned()
    })
}

fn obj_set(name: &str, prop: &str, val: Value) {
    OBJECTS.with(|o| {
        let mut b = o.borrow_mut();
        let m = b.entry(name.to_string()).or_insert_with(HashMap::new);
        m.insert(prop.to_string(), val);
    });
}

fn ensure_obj(name: &str, class: &str) {
    obj_set(name, "type", Value::String(class.to_string()));
    obj_set(name, "name", Value::String(name.to_string()));
}

#[derive(Clone, Debug, PartialEq)]
enum Value {
    Unit,
    Bool(bool),
    Number(f64),
    String(String),
    List(Vec<Value>),
    Object(HashMap<String, Value>),
}

impl Value {
    fn as_number(&self) -> Result<f64, String> {
        match self {
            Value::Number(n) => Ok(*n),
            Value::Unit => Ok(0.0),
            _ => Err("expected number".into()),
        }
    }
    fn as_bool(&self) -> Result<bool, String> {
        match self {
            Value::Bool(b) => Ok(*b),
            Value::Unit => Ok(false),
            Value::Number(n) => Ok(*n != 0.0),
            Value::String(s) => Ok(!s.is_empty()),
            Value::List(xs) => Ok(!xs.is_empty()),
            Value::Object(map) => Ok(!map.is_empty()),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
enum BinOpKind { Add, Sub, Mul, Div, Mod, Eq, Ne, Lt, Le, Gt, Ge, And, Or }
#[derive(Clone, Debug, PartialEq)]
enum UnOpKind { Neg, Not }

#[derive(Clone, Debug, PartialEq)]
enum Instr {
    Const(Value),
    LoadLocal(String),
    StoreLocal(String),
    BinOp(BinOpKind),
    UnOp(UnOpKind),
    Jump(usize),
    JumpIfFalse(usize),
    CallHost(String, usize),
    Call(String, usize),
    BuildList(usize),
    Return,
}

struct Host;

impl Host {
    fn call(name: &str, args: &[Value]) -> Result<Value, String> {
        match name {
            "parse_tiny_source" => {
                // Return a lightweight Program object carrying the source path for delegation.
                // { type: "Program", source_path: <string> }
                let path = match args.get(0) { Some(Value::String(s)) => s.clone(), Some(v) => display_value(v), None => String::new() };
                let mut m = std::collections::HashMap::new();
                m.insert("type".to_string(), Value::String("Program".to_string()));
                m.insert("source_path".to_string(), Value::String(path));
                Ok(Value::Object(m))
            }
            "lower_and_compile" => {
                // Delegate compilation to the Stage 0 interpreter (pat) if available.
                // Accepts: lower_and_compile(programObj[, outPath])
                // programObj is expected to be { type: "Program", source_path: <string> } from parse_tiny_source.
                println!("[host lower_and_compile] ENTER args_len={}", args.len());
                if args.is_empty() { println!("[host lower_and_compile] no args"); return Ok(Value::String(String::new())); }
                let src_path = match &args[0] {
                    Value::Object(map) => match map.get("source_path") { Some(Value::String(s)) => s.clone(), _ => String::new() },
                    Value::String(s) => s.clone(),
                    other => display_value(other),
                };
                let out_opt = args.get(1).map(|v| match v { Value::String(s) => s.clone(), other => display_value(other) });
                println!("[host lower_and_compile] src_path={} out_opt={}", src_path, out_opt.clone().unwrap_or_default());

                // Resolve Stage 0 runner strictly from project-local paths (no PATH fallback)
                let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
                let rel_candidates = [
                    "rust-runtime/target/debug/pat",
                    "rust-runtime/target/debug/pat.exe",
                    "./rust-runtime/target/debug/pat",
                    "./rust-runtime/target/debug/pat.exe",
                    "..\\rust-runtime\\target\\debug\\pat.exe",
                    "rust-runtime\\target\\debug\\pat.exe",
                ];
                let abs_candidates: Vec<String> = rel_candidates.iter()
                    .map(|p| cwd.join(p).display().to_string())
                    .collect();
                let pat_path = abs_candidates.iter().find(|p| std::path::Path::new(p).exists()).cloned();
                let pat_path = match pat_path {
                    Some(p) => p,
                    None => {
                        return Err(format!(
                            "lower_and_compile: could not find project pat runner. Checked:\n{}",
                            abs_candidates.join("\n")
                        ));
                    }
                };
                println!("[host lower_and_compile] using pat at {}", pat_path);
                // Use raw strings, but on Windows convert MSYS-style (/e/...) to Windows (E:\...) for child rustc.
                let script_raw: &str = "./patc_native.patlang";
                let input_raw: String = src_path.clone();
                let out_raw: Option<String> = out_opt.clone();

                #[allow(unused_variables)]
                fn msys_to_win_path(p: &str) -> String {
                    #[cfg(windows)]
                    {
                        let b = p.as_bytes();
                        if b.len() >= 3 && b[0] == b'/' && b[2] == b'/' {
                            let drive = (b[1] as char).to_ascii_uppercase();
                            let rest = &p[3..];
                            let rest_bs = rest.replace('/', "\\");
                            return format!("{}:\\{}", drive, rest_bs);
                        }
                        // Otherwise, just replace forward slashes with backslashes to be safe
                        return p.replace('/', "\\");
                    }
                    #[cfg(not(windows))]
                    {
                        p.to_string()
                    }
                }

                // Make input absolute for reliability
                let input_abs = {
                    let p = std::path::Path::new(&input_raw);
                    if p.is_absolute() { p.to_path_buf() } else { std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from(".")).join(p) }
                };
                let input_arg = msys_to_win_path(&input_abs.display().to_string());
                // For --out: if relative, make it absolute; if not provided, derive a default next to input
                let out_arg: String = match out_raw.as_ref() {
                    Some(s) => {
                        let p = std::path::Path::new(s);
                        if p.is_absolute() {
                            s.clone()
                        } else {
                            match std::env::current_dir() {
                                Ok(cwd) => cwd.join(p).display().to_string(),
                                Err(_) => s.clone(),
                            }
                        }
                    }
                    None => {
                        let in_p = std::path::Path::new(&input_arg);
                        let stem = in_p.file_stem().and_then(|s| s.to_str()).unwrap_or("a");
                        let parent = in_p.parent().unwrap_or_else(|| std::path::Path::new("."));
                        let mut outp = parent.join(stem);
                        if cfg!(windows) { outp.set_extension("exe"); }
                        outp.display().to_string()
                    }
                };

                // Build command: pat --patc <input> [--out path] (direct Stage 0 backend)
                let mut cmd = std::process::Command::new(&pat_path);
                if let Ok(cwd) = std::env::current_dir() { let _ = cmd.current_dir(&cwd); }
                cmd.arg("--patc");
                if !input_arg.is_empty() { cmd.arg(&input_arg); }
                if !out_arg.is_empty() { cmd.arg("--out").arg(&out_arg); }
                cmd.env_remove("RUST_LOG");
                cmd.env_remove("PATLANG_DEBUG");
                // Always print a concise debug line to aid bootstrap troubleshooting and write to a local log file
                let cwd_dbg = std::env::current_dir().ok().map(|p| p.display().to_string()).unwrap_or_default();
                println!(
                    "[host lower_and_compile] cwd={} using_pat={} cmd: pat --patc {:?} {}",
                    cwd_dbg,
                    pat_path,
                    input_arg,
                    format!("--out {:?}", out_arg)
                );
                if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open("boot_host.log") {
                    use std::io::Write;
                    let _ = writeln!(f, "cwd={} pat={} cmd: pat --patc {} --out {}", cwd_dbg, pat_path, input_arg, out_arg);
                }
                println!("[host lower_and_compile] spawning child...");
                let out = cmd.output().map_err(|e| format!("lower_and_compile: failed to spawn pat: {}", e))?;
                println!("[host lower_and_compile] DONE status={} stdout={} stderr={}", out.status, String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
                if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open("boot_host.log") {
                    use std::io::Write;
                    let _ = writeln!(f, "status={} stdout_len={} stderr_len={}", out.status, out.stdout.len(), out.stderr.len());
                }
                if !out.status.success() {
                    let stderr = String::from_utf8_lossy(&out.stderr).to_string();
                    return Err(format!("lower_and_compile: pat exited with {}\n{}", out.status, stderr));
                }
                // If caller provided an explicit out path, prefer it and require it to exist
                // Verify derived/provided out exists
                let p = std::path::Path::new(&out_arg);
                if p.exists() {
                    if let Ok(canon) = std::fs::canonicalize(p) { return Ok(Value::String(format!("{}", canon.display()))); }
                    return Ok(Value::String(out_arg.clone()));
                }
                // Fallback: MSYS→Windows translation check
                let p_win = msys_to_win_path(&out_arg);
                let p2 = std::path::Path::new(&p_win);
                if p2.exists() {
                    if let Ok(canon) = std::fs::canonicalize(p2) { return Ok(Value::String(format!("{}", canon.display()))); }
                    return Ok(Value::String(p_win));
                }
                let stdout = String::from_utf8_lossy(&out.stdout).to_string();
                Err(format!(
                    "lower_and_compile: pat reported success but output not found at '{}'.\nChecked also '{}'.\nstdout: {}",
                    out_arg, p_win, stdout
                ))
            }
            "get_argv" => {
                // Mimic `pat ./patc_native.patlang <input> [--out path]` argv shape expected by patc_native:
                // Prepend a synthetic script name so indexing matches (argv[0] is the script path).
                let mut rest: Vec<String> = std::env::args().collect();
                if !rest.is_empty() { rest.remove(0); }
                let mut full = Vec::with_capacity(rest.len()+1);
                full.push("./patc_native.patlang".to_string());
                full.extend(rest);
                Ok(Value::List(full.into_iter().map(Value::String).collect()))
            }
            "list_get" => {
                // list_get(list, index)
                if args.len() != 2 { return Err("expected 2 args".into()); }
                let idx = match &args[1] { Value::Number(n) => *n as usize, Value::String(s) => s.parse::<usize>().unwrap_or(0), _ => 0 };
                match &args[0] {
                    Value::List(xs) => Ok(xs.get(idx).cloned().unwrap_or(Value::Unit)),
                    Value::String(s) => {
                        let ch = s.chars().nth(idx).unwrap_or('\0');
                        Ok(Value::String(if ch == '\0' { String::new() } else { ch.to_string() }))
                    }
                    _ => Ok(Value::Unit),
                }
            }
            "list_len" => {
                // list_len(listOrString) -> String count (to match Stage 0 builtins)
                if args.len() != 1 { return Err("expected 1 arg".into()); }
                let n = match &args[0] {
                    Value::List(xs) => xs.len(),
                    Value::String(s) => s.chars().count(),
                    _ => 0,
                };
                Ok(Value::String(n.to_string()))
            }
            "infer_type_for" => {
                // args: pred, index, class
                if args.len() != 3 { return Ok(Value::Unit); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let idx = match &args[1] { Value::Number(n) => *n as usize, Value::String(s) => s.parse::<usize>().unwrap_or(0), _ => 0 };
                let class = match &args[2] { Value::String(s) => s.clone(), _ => String::new() };
                TYPE_RULES.with(|tr| { tr.borrow_mut().insert((pred, idx), class); });
                Ok(Value::Unit)
            }
            "fact" => {
                if args.len() != 3 { return Ok(Value::Unit); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let a = to_s(args.get(1).unwrap_or(&Value::Unit));
                let b = to_s(args.get(2).unwrap_or(&Value::Unit));
                FACTS.with(|f| {
                    let mut m = f.borrow_mut();
                    m.entry(pred).or_insert_with(Vec::new).push((a, b));
                });
                Ok(Value::Unit)
            }
            "goal" => {
                if args.is_empty() { return Ok(Value::Unit); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let mut items: Vec<String> = Vec::new();
                for a in &args[1..] { items.push(to_s(a)); }
                GOALS.with(|g| { g.borrow_mut().push((pred, items)); });
                Ok(Value::Unit)
            }
            "query" => {
                if args.len() != 3 { return Ok(Value::Number(0.0)); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let a = to_s(args.get(1).unwrap_or(&Value::Unit));
                let mut count = 0usize;
                let mut bs: Vec<String> = Vec::new();
                FACTS.with(|f| {
                    if let Some(v) = f.borrow().get(&pred) {
                        for (x, b) in v.iter() {
                            if x == &a { count += 1; bs.push(b.clone()); }
                        }
                    }
                });
                // Apply simple type inference rules recorded
                TYPE_RULES.with(|tr| {
                    let rules = tr.borrow();
                    if let Some(class0) = rules.get(&(pred.clone(), 0usize)) { ensure_obj(&a, class0); }
                    if let Some(class1) = rules.get(&(pred.clone(), 1usize)) {
                        for b in bs.iter() { ensure_obj(b, class1); }
                    }
                });
                Ok(Value::Number(count as f64))
            }
            "new" => {
                if args.len() != 2 { return Ok(Value::Unit); }
                let class = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let name = match &args[1] { Value::String(s) => s.clone(), _ => String::new() };
                if !name.is_empty() { ensure_obj(&name, &class); }
                Ok(Value::String(name))
            }
            "set_var" => {
                if args.len() != 2 { return Ok(Value::Unit); }
                let key = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let val = args.get(1).cloned().unwrap_or(Value::Unit);
                if !key.is_empty() {
                    OBJECTS.with(|o| {
                        let mut b = o.borrow_mut();
                        let m = b.entry("__vars".to_string()).or_insert_with(HashMap::new);
                        m.insert(key, val);
                    });
                }
                Ok(Value::Unit)
            }
            "print" => {
                if let Some(x) = args.get(0) {
                    // Support simple string interpolation for IR runtime: "#{var}"
                    let s = display_value(x);
                    let out = interpolate(&s);
                    println!("{}", out);
                }
                Ok(Value::Unit)
            },
            "sed" => {
                // sed("s/pat/repl/[flags]", input)
                let cmd = match args.get(0) { Some(Value::String(s)) => s.as_str(), _ => "" };
                let dv;
                let input: &str = match args.get(1) {
                    Some(Value::String(s)) => s.as_str(),
                    Some(v) => { dv = display_value(v); dv.as_str() },
                    None => "",
                };
                let out = sed_command(cmd, input);
                Ok(Value::String(out))
            },
            "add" => host_bin_num(args, |a,b| a+b),
            "multiply" => host_bin_num(args, |a,b| a*b),
            "subtract" => host_bin_num(args, |a,b| a-b),
            "max" => host_bin_num(args, |a,b| a.max(b)),
            "min" => host_bin_num(args, |a,b| a.min(b)),
            "calculate" => Ok(Value::Number(0.0)),
            "calculate_result" => Ok(Value::Number(0.0)),
            "get_value" => Ok(Value::Number(0.0)),
            "process" => Ok(Value::Bool(true)),
            "validate" => Ok(Value::Bool(true)),
            "len" => {
                let v = args.get(0).cloned().unwrap_or(Value::Unit);
                let n = match v {
                    Value::String(s) => s.chars().count() as f64,
                    Value::List(xs) => xs.len() as f64,
                    Value::Object(m) => m.len() as f64,
                    Value::Unit => 0.0,
                    _ => 0.0,
                };
                Ok(Value::Number(n))
            }
            "get" => {
                if args.len() != 2 { return Err("expected 2 args".into()); }
                let key = match &args[1] { Value::String(s) => s.clone(), _ => return Err("expected string key".into()) };
                match &args[0] {
                    Value::String(name) => Ok(obj_get(name, &key).unwrap_or(Value::Unit)),
                    Value::Object(map) => Ok(map.get(&key).cloned().unwrap_or(Value::Unit)),
                    _ => Ok(Value::Unit),
                }
            }
            "send" => {
                if args.len() < 2 { return Ok(Value::Unit); }
                let recv = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let method = match &args[1] { Value::String(s) => s.clone(), _ => String::new() };
                let rest = &args[2..];
                match method.as_str() {
                    "set" => {
                        if rest.len() != 2 { return Ok(Value::Unit); }
                        let prop = match &rest[0] { Value::String(s) => s.clone(), _ => String::new() };
                        let val = rest[1].clone();
                        if !recv.is_empty() && !prop.is_empty() { obj_set(&recv, &prop, val); }
                        Ok(Value::Unit)
                    }
                    "infer_is_adult" => {
                        // reads age, sets is_adult when >= 18
                        if let Some(Value::Number(age)) = obj_get(&recv, "age") {
                            if age >= 18.0 { obj_set(&recv, "is_adult", Value::Bool(true)); return Ok(Value::Bool(true)); }
                        } else if let Some(Value::String(s)) = obj_get(&recv, "age") {
                            if s.parse::<f64>().unwrap_or(0.0) >= 18.0 { obj_set(&recv, "is_adult", Value::Bool(true)); return Ok(Value::Bool(true)); }
                        }
                        Ok(Value::Bool(false))
                    }
                    "infer_relations" => {
                        // if exists fact("parent", X, recv) then set has_parent true
                        let mut has = false;
                        FACTS.with(|f| {
                            if let Some(v) = f.borrow().get("parent") {
                                has = v.iter().any(|(_, child)| child == &recv);
                            }
                        });
                        if has { obj_set(&recv, "has_parent", Value::Bool(true)); return Ok(Value::Bool(true)); }
                        Ok(Value::Bool(false))
                    }
                    _ => Ok(Value::Unit),
                }
            }
            other => Err(format!("host fn '{}' not found", other)),
        }
    }
}

fn host_bin_num(args: &[Value], f: fn(f64,f64)->f64) -> Result<Value, String> {
    let a = args.get(0).ok_or("expected 2 args")?;
    let b = args.get(1).ok_or("expected 2 args")?;
    let an = a.as_number()?; let bn = b.as_number()?;
    Ok(Value::Number(f(an,bn)))
}

fn display_value(v: &Value) -> String {
    match v {
        Value::Unit => String::new(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => if n.fract()==0.0 { format!("{}", *n as i64) } else { n.to_string() },
        Value::String(s) => s.clone(),
        Value::List(xs) => {
            let parts: Vec<String> = xs.iter().map(|x| display_value(x)).collect();
            format!("[{}]", parts.join(", "))
        }
        Value::Object(map) => {
            let mut kvs: Vec<String> = map.iter().map(|(k,v)| format!("{}: {}", k, display_value(v))).collect();
            kvs.sort();
            format!("{{{}}}", kvs.join(", "))
        }
    }
}

fn sed_command(cmd: &str, input: &str) -> String {
    if !cmd.starts_with('s') { return input.to_string(); }
    let mut parts = cmd.splitn(4, '/');
    let _s = parts.next();
    let pat = match parts.next() { Some(p) => p, None => return input.to_string() };
    let repl = match parts.next() { Some(r) => r, None => return input.to_string() };
    let flags = parts.next().unwrap_or("");
    let global = flags.contains('g');
    let ci = flags.contains('i');
    replace_lit(input, pat, repl, global, ci)
}

fn replace_lit(hay: &str, pat: &str, rep: &str, global: bool, ci: bool) -> String {
    if pat.is_empty() { return hay.to_string(); }
    if !ci {
        if !global {
            if let Some(pos) = hay.find(pat) {
                let mut out = String::with_capacity(hay.len());
                out.push_str(&hay[..pos]);
                out.push_str(rep);
                out.push_str(&hay[pos+pat.len()..]);
                return out;
            }
            return hay.to_string();
        } else {
            let mut out = String::with_capacity(hay.len());
            let mut start = 0usize;
            let mut rest = hay;
            while let Some(pos) = rest.find(pat) {
                let abs = start + pos;
                out.push_str(&hay[start..abs]);
                out.push_str(rep);
                start = abs + pat.len();
                rest = &hay[start..];
            }
            out.push_str(&hay[start..]);
            return out;
        }
    }
    let hay_l = hay.to_ascii_lowercase();
    let pat_l = pat.to_ascii_lowercase();
    if !global {
        if let Some(pos) = hay_l.find(&pat_l) {
            let mut out = String::with_capacity(hay.len());
            out.push_str(&hay[..pos]);
            out.push_str(rep);
            out.push_str(&hay[pos+pat.len()..]);
            return out;
        }
        return hay.to_string();
    } else {
        let mut out = String::with_capacity(hay.len());
        let mut start = 0usize;
        let mut idx = 0usize;
        while idx <= hay_l.len() {
            if let Some(pos) = hay_l[idx..].find(&pat_l) {
                let abs = idx + pos;
                out.push_str(&hay[start..abs]);
                out.push_str(rep);
                start = abs + pat.len();
                idx = start;
            } else { break; }
        }
        out.push_str(&hay[start..]);
        return out;
    }
}

// Simple interpolation: replace occurrences of #{name} using OBJECTS store vars or event locals if provided in scope.
fn interpolate(input: &str) -> String {
    let mut out = String::new();
    let b = input.as_bytes();
    let mut i = 0usize;
    while i < b.len() {
        if i + 2 < b.len() && b[i] as char == '#' && b[i+1] as char == '{' {
            i += 2; let start = i;
            while i < b.len() && b[i] as char != '}' { i += 1; }
            let key = &input[start..i];
            let val = resolve_interp_var(key);
            out.push_str(&val);
            if i < b.len() && b[i] as char == '}' { i += 1; }
        } else { out.push(b[i] as char); i += 1; }
    }
    out
}

fn resolve_interp_var(key: &str) -> String {
    // Try OBJECTS first (object.name property), then fall back to key itself.
    if let Some((obj, prop)) = key.split_once('.') {
        if let Some(v) = obj_get(obj, prop) { return display_value(&v); }
    } else {
        // No dot: may refer to a plain variable set on a synthetic "__vars" object by handlers.
        if let Some(v) = obj_get("__vars", key) { return display_value(&v); }
    }
    String::new()
}

#[derive(Clone)]
struct Function { name: String, params: Vec<String>, body: Vec<Instr> }

struct Program { functions: HashMap<String, Function>, entry: String }

fn run(program: &Program) -> Result<Value,String> {
    let entry = program.functions.get(&program.entry).ok_or("entry not found")?;
    run_function(program, entry, &[])
}

fn run_function(program: &Program, func: &Function, args: &[Value]) -> Result<Value,String> {
    let mut pc: usize = 0;
    let mut stack: Vec<Value> = Vec::new();
    let mut locals: HashMap<String, Value> = HashMap::new();
    // bind params
    for (i, p) in func.params.iter().enumerate() { if let Some(v) = args.get(i) { locals.insert(p.clone(), v.clone()); } }
    while pc < func.body.len() {
        match &func.body[pc] {
            Instr::Const(v) => stack.push(v.clone()),
            Instr::LoadLocal(n) => stack.push(locals.get(n).cloned().unwrap_or(Value::Unit)),
            Instr::StoreLocal(n) => { let v = stack.pop().ok_or("stack underflow")?; locals.insert(n.clone(), v); },
            Instr::UnOp(k) => {
                let a = stack.pop().ok_or("stack underflow")?;
                let r = match k { UnOpKind::Neg => Value::Number(-a.as_number()?), UnOpKind::Not => Value::Bool(!a.as_bool()?) };
                stack.push(r);
            }
            Instr::BinOp(k) => {
                use BinOpKind::*;
                let b = stack.pop().ok_or("stack underflow")?;
                let a = stack.pop().ok_or("stack underflow")?;
                let r = match k {
                    Add => add(&a,&b)?, Sub => sub(&a,&b)?, Mul => mul(&a,&b)?, Div => div(&a,&b)?, Mod => modu(&a,&b)?,
                    Eq|Ne|Lt|Le|Gt|Ge => cmp(k, &a, &b)?,
                    And => Value::Bool(a.as_bool()? && b.as_bool()?),
                    Or => Value::Bool(a.as_bool()? || b.as_bool()?),
                };
                stack.push(r);
            }
            Instr::Jump(t) => { pc = *t; continue; }
            Instr::JumpIfFalse(t) => { let c = stack.pop().ok_or("stack underflow")?; if !c.as_bool()? { pc = *t; continue; } }
            Instr::CallHost(n, argc) => {
                let argc = *argc; if stack.len() < argc { return Err("stack underflow".into()); }
                let args_index = stack.len() - argc; let args: Vec<Value> = stack.drain(args_index..).collect();
                if n == "emit" {
                    let ev = match args.get(0) { Some(Value::String(s)) => s.clone(), _ => String::new() };
                    let payload = args.get(1).cloned().unwrap_or(Value::Unit);
                    let mut last = Value::Unit;
                    let handlers: Vec<String> = EVENT_HANDLERS.with(|m| m.borrow().get(&ev).cloned().unwrap_or_default());
                    for h in handlers {
                        let callee = program.functions.get(&h).ok_or_else(|| format!("function '{}' not found", h))?;
                        // Expose event locals for interpolation via __vars as well
                        obj_set("__vars", "event_name", Value::String(ev.clone()));
                        obj_set("__vars", "event_data", payload.clone());
                        // Handlers are synthesized with parameters (event_name, event_data)
                        last = run_function(program, callee, &[Value::String(ev.clone()), payload.clone()])?;
                    }
                    stack.push(last);
                } else {
                    let r = Host::call(n, &args)?; stack.push(r);
                }
            }
            Instr::Call(n, argc) => {
                let argc = *argc; if stack.len() < argc { return Err("stack underflow".into()); }
                let args_index = stack.len() - argc; let args: Vec<Value> = stack.drain(args_index..).collect();
                let callee = program.functions.get(n).ok_or_else(|| format!("function '{}' not found", n))?;
                let r = run_function(program, callee, &args)?; stack.push(r);
            }
            Instr::BuildList(n) => { let n=*n; if stack.len()<n {return Err("stack underflow".into());} let start=stack.len()-n; let items: Vec<Value>=stack.drain(start..).collect(); stack.push(Value::List(items)); }
            Instr::Return => { return Ok(stack.pop().unwrap_or(Value::Unit)); }
        }
        pc += 1;
    }
    Ok(stack.pop().unwrap_or(Value::Unit))
}

fn add(a:&Value,b:&Value)->Result<Value,String>{
    match (a,b) {
        (Value::String(sa), _) => Ok(Value::String(format!("{}{}", sa, to_s(b)))),
        (_, Value::String(sb)) => Ok(Value::String(format!("{}{}", to_s(a), sb))),
        _ => Ok(Value::Number(a.as_number()? + b.as_number()?)),
    }
}
fn sub(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? - b.as_number()?)) }
fn mul(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? * b.as_number()?)) }
fn div(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? / b.as_number()?)) }
fn modu(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? % b.as_number()?)) }
fn cmp(k:&BinOpKind,a:&Value,b:&Value)->Result<Value,String>{
    use BinOpKind::*;
    let res = match k {
        // Structural equality for Eq/Ne across all Value variants
        Eq => a == b,
        Ne => a != b,
        // Relational ops are numeric-only comparisons
        Lt | Le | Gt | Ge => {
            let (an, bn) = (a.as_number()?, b.as_number()?);
            match k {
                Lt => an < bn,
                Le => an <= bn,
                Gt => an > bn,
                Ge => an >= bn,
                _ => unreachable!(),
            }
        }
        _ => false,
    };
    Ok(Value::Bool(res))
}
fn to_s(v:&Value)->String{ match v { Value::Unit=>String::new(), Value::Bool(b)=>b.to_string(), Value::Number(n)=> if n.fract()==0.0 {format!("{}",*n as i64)} else {n.to_string()}, Value::String(s)=>s.clone(), Value::List(xs)=>{ let parts:Vec<String>=xs.iter().map(|x|to_s(x)).collect(); format!("[{}]", parts.join(", ")) }, Value::Object(map)=>{ let mut kvs:Vec<String>=map.iter().map(|(k,v)| format!("{}: {}",k,to_s(v))).collect(); kvs.sort(); format!("{{{}}}", kvs.join(", ")) } } }

fn main(){
    let program = build_program();
    match run(&program) { Ok(v) => println!("{}", display_value(&v)), Err(e) => { eprintln!("IR runtime error: {}", e); std::process::exit(1); } }
}

fn build_program() -> Program {
    let mut functions: HashMap<String, Function> = HashMap::new();
    // Seed event handlers registry from embedded Program
    EVENT_HANDLERS.with(|m| { let mut mm = m.borrow_mut();
    });
    // function main
    let mut body: Vec<Instr> = Vec::new();
    body.push(Instr::CallHost("get_argv".to_string(), 0));
    body.push(Instr::StoreLocal("argv".to_string()));
    body.push(Instr::LoadLocal("argv".to_string()));
    body.push(Instr::CallHost("list_len".to_string(), 1));
    body.push(Instr::StoreLocal("argc".to_string()));
    body.push(Instr::LoadLocal("argc".to_string()));
    body.push(Instr::Const(Value::String("0".to_string())));
    body.push(Instr::BinOp(BinOpKind::Eq));
    body.push(Instr::JumpIfFalse(12));
    body.push(Instr::Const(Value::String("usage: <compiler> <input.patlang> [--out path]".to_string())));
    body.push(Instr::CallHost("print".to_string(), 1));
    body.push(Instr::Jump(43));
    body.push(Instr::LoadLocal("argv".to_string()));
    body.push(Instr::Const(Value::Number(1.0)));
    body.push(Instr::CallHost("list_get".to_string(), 2));
    body.push(Instr::StoreLocal("input".to_string()));
    body.push(Instr::LoadLocal("argv".to_string()));
    body.push(Instr::Const(Value::Number(2.0)));
    body.push(Instr::CallHost("list_get".to_string(), 2));
    body.push(Instr::StoreLocal("flag".to_string()));
    body.push(Instr::Const(Value::String("".to_string())));
    body.push(Instr::StoreLocal("out".to_string()));
    body.push(Instr::LoadLocal("flag".to_string()));
    body.push(Instr::Const(Value::String("--out".to_string())));
    body.push(Instr::BinOp(BinOpKind::Eq));
    body.push(Instr::JumpIfFalse(31));
    body.push(Instr::LoadLocal("argv".to_string()));
    body.push(Instr::Const(Value::Number(3.0)));
    body.push(Instr::CallHost("list_get".to_string(), 2));
    body.push(Instr::StoreLocal("out".to_string()));
    body.push(Instr::Jump(31));
    body.push(Instr::LoadLocal("input".to_string()));
    body.push(Instr::CallHost("parse_tiny_source".to_string(), 1));
    body.push(Instr::StoreLocal("prog".to_string()));
    body.push(Instr::Const(Value::String("CALL".to_string())));
    body.push(Instr::CallHost("print".to_string(), 1));
    body.push(Instr::LoadLocal("out".to_string()));
    body.push(Instr::Const(Value::String("".to_string())));
    body.push(Instr::BinOp(BinOpKind::Eq));
    body.push(Instr::JumpIfFalse(41));
    body.push(Instr::Jump(41));
    body.push(Instr::Const(Value::String("RET".to_string())));
    body.push(Instr::CallHost("print".to_string(), 1));
    body.push(Instr::Return);
    let params: Vec<String> = vec![];
    functions.insert("main".to_string(), Function { name: "main".to_string(), params, body });
    Program { functions, entry: "main".to_string() }
}
