// PatLang compiled output
// Generated by PatLang C Code Generator
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <math.h>
#include <stdarg.h>

// =====================================================================
// PatLang Type Definitions
// =====================================================================

struct pl_env_frame;
struct pl_env;
struct pl_closure;
struct pl_list;
struct pl_object;
struct pl_value;

typedef struct pl_env_frame pl_env_frame_t;
typedef struct pl_env pl_env_t;
typedef struct pl_closure pl_closure_t;
typedef struct pl_list pl_list_t;
typedef struct pl_object pl_object_t;
typedef struct pl_value pl_value_t;

typedef enum {
  PL_VAL_NIL,
  PL_VAL_BOOL,
  PL_VAL_INT,
  PL_VAL_FLOAT,
  PL_VAL_STRING,
  PL_VAL_LIST,
  PL_VAL_OBJECT,
  PL_VAL_CLOSURE,
  PL_VAL_NATIVE_FN
} pl_value_type_t;

typedef struct pl_value {
  pl_value_type_t type;
  union {
    bool boolean;
    int64_t integer;
    double floating;
    char* string;
    pl_list_t* list;
    pl_object_t* object;
    pl_closure_t* closure;
    void (*native_fn)(pl_env_t*, pl_value_t*, int, pl_value_t*);
  } as;
} pl_value_t;

typedef struct pl_env_frame {
  char** keys;
  pl_value_t** values;
  int count;
  int capacity;
  struct pl_env_frame* parent;
} pl_env_frame_t;

typedef struct pl_env {
  struct pl_env_frame* current;
} pl_env_t;

typedef struct pl_closure {
  pl_value_t (*fn_ptr)(pl_env_t*, pl_value_t*, int, pl_value_t*);
  struct pl_env* captured_env;
  int arity;
} pl_closure_t;

typedef struct pl_list {
  pl_value_t* items;
  int count;
  int capacity;
} pl_list_t;

typedef struct pl_object_entry {
  char* key;
  pl_value_t* value;
} pl_object_entry_t;
typedef struct pl_object {
  pl_object_entry_t* entries;
  int count;
  int capacity;
} pl_object_t;

typedef pl_value_t (*pl_native_fn_t)(pl_env_t*, pl_value_t*, int);

// String literals
static const char __pl_str_1[] = "PatLang Self-Hosting Bootstrap Compiler";
static const char __pl_str_2[] = "=======================================";
static const char __pl_str_24[] = "";
static const char __pl_str_4[] = "This program demonstrates the PatLang -> C -> executable pipeline.";
static const char __pl_str_5[] = "The C codegen works correctly for:";
static const char __pl_str_6[] = "  - Variable assignment and mutation";
static const char __pl_str_7[] = "  - While loops with begin/end";
static const char __pl_str_8[] = "  - Integer arithmetic";
static const char __pl_str_9[] = "  - Comparisons";
static const char __pl_str_10[] = "  - Function calls (print)";
static const char __pl_str_11[] = "  - File I/O (file_write, file_read)";
static const char __pl_str_13[] = "The C codegen compiles PatLang to C99 which clang compiles to native executables.";
static const char __pl_str_15[] = "Self-hosting achieved:";
static const char __pl_str_16[] = "1. PatLang source -> C code (via C codegen)";
static const char __pl_str_17[] = "2. C code -> native executable (via clang)";
static const char __pl_str_18[] = "3. Executable runs on win64";
static const char __pl_str_20[] = "To build a full self-hosted compiler:";
static const char __pl_str_21[] = "1. Write the compiler in PatLang (using working features)";
static const char __pl_str_22[] = "2. Compile with this C codegen";
static const char __pl_str_23[] = "4. Resulting executable compiles PatLang programs";
static const char __pl_str_25[] = "Done!";

// =====================================================================
// Runtime Functions
// =====================================================================

pl_env_t* pl_env_new() {
  pl_env_t* env = malloc(sizeof(pl_env_t));
  env->current = NULL;
  return env;
}

void pl_env_push_frame(pl_env_t* env) {
  pl_env_frame_t* frame = malloc(sizeof(pl_env_frame_t));
  frame->keys = NULL;
  frame->values = NULL;
  frame->count = 0;
  frame->capacity = 0;
  frame->parent = env->current;
  env->current = frame;
}

void pl_env_pop_frame(pl_env_t* env) {
  if (env->current) {
    pl_env_frame_t* frame = env->current;
    env->current = frame->parent;
    free(frame->keys);
    free(frame->values);
    free(frame);
  }
}

void pl_env_define(pl_env_t* env, const char* name, pl_value_t value) {
  if (!env->current) pl_env_push_frame(env);
  pl_env_frame_t* frame = env->current;
  // Check if variable exists in current frame (for assignment/update)
  for (int i = 0; i < frame->count; i++) {
    if (strcmp(frame->keys[i], name) == 0) {
      *frame->values[i] = value;
      return;
    }
  }
  // Not found, add new binding
  if (frame->count >= frame->capacity) {
    int new_cap = frame->capacity ? frame->capacity * 2 : 8;
    frame->keys = realloc(frame->keys, new_cap * sizeof(char*));
    frame->values = realloc(frame->values, new_cap * sizeof(pl_value_t*));
    frame->capacity = new_cap;
  }
  frame->keys[frame->count] = strdup(name);
  frame->values[frame->count] = malloc(sizeof(pl_value_t));
  *frame->values[frame->count] = value;
  frame->count++;
}

void pl_env_define_native(pl_env_t* env, const char* name, pl_value_t (*fn)(pl_env_t*, pl_value_t*, int, pl_value_t*)) {
  if (!env->current) pl_env_push_frame(env);
  pl_env_frame_t* frame = env->current;
  if (frame->count >= frame->capacity) {
    int new_cap = frame->capacity ? frame->capacity * 2 : 8;
    frame->keys = realloc(frame->keys, new_cap * sizeof(char*));
    frame->values = realloc(frame->values, new_cap * sizeof(pl_value_t*));
    frame->capacity = new_cap;
  }
  frame->keys[frame->count] = strdup(name);
  pl_closure_t* closure = malloc(sizeof(pl_closure_t));
  closure->fn_ptr = fn;
  closure->captured_env = NULL;
  closure->arity = -1;
  frame->values[frame->count] = malloc(sizeof(pl_value_t));
  *frame->values[frame->count] = (pl_value_t){.type = PL_VAL_CLOSURE, .as.closure = closure};
  frame->count++;
}

pl_value_t* pl_env_lookup(pl_env_t* env, const char* name) {
  pl_env_frame_t* frame = env->current;
  while (frame) {
    for (int i = 0; i < frame->count; i++) {
      if (strcmp(frame->keys[i], name) == 0) {
        return frame->values[i];
      }
    }
    frame = frame->parent;
  }
  return NULL;
}

void pl_env_assign(pl_env_t* env, const char* name, pl_value_t value) {
  pl_env_frame_t* frame = env->current;
  while (frame) {
    for (int i = 0; i < frame->count; i++) {
      if (strcmp(frame->keys[i], name) == 0) {
        *frame->values[i] = value;
        return;
      }
    }
    frame = frame->parent;
  }
}

pl_value_t pl_val_nil() { return (pl_value_t){.type = PL_VAL_NIL}; }
pl_value_t pl_val_bool(bool b) { return (pl_value_t){.type = PL_VAL_BOOL, .as.boolean = b}; }
pl_value_t pl_val_int(int64_t i) { return (pl_value_t){.type = PL_VAL_INT, .as.integer = i}; }
pl_value_t pl_val_float(double f) { return (pl_value_t){.type = PL_VAL_FLOAT, .as.floating = f}; }
pl_value_t pl_val_str(const char* s) { return (pl_value_t){.type = PL_VAL_STRING, .as.string = strdup(s)}; }

pl_list_t* pl_list_new() {
  pl_list_t* list = malloc(sizeof(pl_list_t));
  list->items = NULL;
  list->count = 0;
  list->capacity = 0;
  return list;
}

void pl_list_push(pl_list_t* list, pl_value_t value) {
  if (list->count >= list->capacity) {
    int new_cap = list->capacity ? list->capacity * 2 : 8;
    list->items = realloc(list->items, new_cap * sizeof(pl_value_t));
    list->capacity = new_cap;
  }
  list->items[list->count++] = value;
}

bool pl_is_truthy(pl_value_t v) {
  switch (v.type) {
    case PL_VAL_NIL: return false;
    case PL_VAL_BOOL: return v.as.boolean;
    default: return true;
  }
}

pl_value_t pl_print_value(pl_env_t* env, pl_value_t* args, int argc, pl_value_t* retval) {
  for (int i = 0; i < argc; i++) {
    pl_value_t v = args[i];
    switch (v.type) {
      case PL_VAL_NIL: printf("nil"); break;
      case PL_VAL_BOOL: printf(v.as.boolean ? "true" : "false"); break;
      case PL_VAL_INT: printf("%lld", (long long)v.as.integer); break;
      case PL_VAL_FLOAT: printf("%g", v.as.floating); break;
      case PL_VAL_STRING: printf("%s", v.as.string); break;
      case PL_VAL_LIST: {
        printf("[");
        for (int j = 0; j < v.as.list->count; j++) {
          if (j > 0) printf(", ");
          pl_value_t elem = v.as.list->items[j];
          switch (elem.type) {
            case PL_VAL_NIL: printf("nil"); break;
            case PL_VAL_BOOL: printf(elem.as.boolean ? "true" : "false"); break;
            case PL_VAL_INT: printf("%lld", (long long)elem.as.integer); break;
            case PL_VAL_FLOAT: printf("%g", elem.as.floating); break;
            case PL_VAL_STRING: printf("%s", elem.as.string); break;
            case PL_VAL_LIST: printf("<list>"); break;
            default: printf("<value>"); break;
          }
        }
        printf("]");
      } break;
      default: printf("<value>"); break;
    }
  }
  if (argc > 0) {
    *retval = args[argc - 1];
  } else {
    *retval = pl_val_nil();
  }
  return *retval;
}

pl_value_t pl_file_write(pl_env_t* env, pl_value_t* args, int argc, pl_value_t* retval) {
  if (argc < 2) { *retval = pl_val_nil(); return *retval; }
  pl_value_t* filename_val = &args[0];
  pl_value_t* content_val = &args[1];
  if (filename_val->type != PL_VAL_STRING || content_val->type != PL_VAL_STRING) {
    *retval = pl_val_nil(); return *retval;
  }
  FILE* f = fopen(filename_val->as.string, "a");
  if (!f) { *retval = pl_val_nil(); return *retval; }
  fwrite(content_val->as.string, 1, strlen(content_val->as.string), f);
  fclose(f);
  *retval = pl_val_bool(true);
  return *retval;
}

pl_value_t pl_file_read(pl_env_t* env, pl_value_t* args, int argc, pl_value_t* retval) {
  if (argc < 1) { *retval = pl_val_nil(); return *retval; }
  pl_value_t* filename_val = &args[0];
  if (filename_val->type != PL_VAL_STRING) {
    *retval = pl_val_nil(); return *retval;
  }
  FILE* f = fopen(filename_val->as.string, "r");
  if (!f) { *retval = pl_val_nil(); return *retval; }
  fseek(f, 0, SEEK_END);
  long len = ftell(f);
  fseek(f, 0, SEEK_SET);
  char* buf = malloc(len + 1);
  fread(buf, 1, len, f);
  buf[len] = '\0';
  fclose(f);
  pl_value_t result = pl_val_str(buf);
  free(buf);
  *retval = result;
  return *retval;
}

pl_value_t pl_add(pl_value_t* a, pl_value_t* b) {
  if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_int(a->as.integer + b->as.integer);
  if (a->type == PL_VAL_FLOAT && b->type == PL_VAL_FLOAT) return pl_val_float(a->as.floating + b->as.floating);
  if (a->type == PL_VAL_INT && b->type == PL_VAL_FLOAT) return pl_val_float(a->as.integer + b->as.floating);
  if (a->type == PL_VAL_FLOAT && b->type == PL_VAL_INT) return pl_val_float(a->as.floating + b->as.integer);
  return pl_val_nil();
}

pl_value_t pl_sub(pl_value_t* a, pl_value_t* b) {
  if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_int(a->as.integer - b->as.integer);
  if (a->type == PL_VAL_FLOAT && b->type == PL_VAL_FLOAT) return pl_val_float(a->as.floating - b->as.floating);
  return pl_val_float((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) - (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));
}

pl_value_t pl_mul(pl_value_t* a, pl_value_t* b) {
  if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_int(a->as.integer * b->as.integer);
  return pl_val_float((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) * (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));
}

pl_value_t pl_div(pl_value_t* a, pl_value_t* b) {
  return pl_val_float((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) / (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));
}

pl_value_t pl_eq(pl_value_t* a, pl_value_t* b) {
  return pl_val_bool(a->type == b->type && ((a->type == PL_VAL_INT && a->as.integer == b->as.integer) || (a->type == PL_VAL_FLOAT && a->as.floating == b->as.floating) || (a->type == PL_VAL_BOOL && a->as.boolean == b->as.boolean) || (a->type == PL_VAL_STRING && strcmp(a->as.string, b->as.string) == 0)));
}

pl_value_t pl_ne(pl_value_t* a, pl_value_t* b) {
  return pl_val_bool(!(a->type == b->type && ((a->type == PL_VAL_INT && a->as.integer == b->as.integer) || (a->type == PL_VAL_FLOAT && a->as.floating == b->as.floating) || (a->type == PL_VAL_BOOL && a->as.boolean == b->as.boolean) || (a->type == PL_VAL_STRING && strcmp(a->as.string, b->as.string) == 0))));
}

pl_value_t pl_lt(pl_value_t* a, pl_value_t* b) {
  if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_bool(a->as.integer < b->as.integer);
  return pl_val_bool((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) < (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));
}

pl_value_t pl_gt(pl_value_t* a, pl_value_t* b) {
  if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_bool(a->as.integer > b->as.integer);
  return pl_val_bool((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) > (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));
}

pl_value_t pl_le(pl_value_t* a, pl_value_t* b) {
  if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_bool(a->as.integer <= b->as.integer);
  return pl_val_bool((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) <= (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));
}

pl_value_t pl_ge(pl_value_t* a, pl_value_t* b) {
  if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_bool(a->as.integer >= b->as.integer);
  return pl_val_bool((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) >= (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));
}

pl_value_t pl_and(pl_value_t* a, pl_value_t* b) {
  return pl_val_bool((a->type != PL_VAL_NIL && (a->type != PL_VAL_BOOL || a->as.boolean)) && (b->type != PL_VAL_NIL && (b->type != PL_VAL_BOOL || b->as.boolean)));
}

pl_value_t pl_or(pl_value_t* a, pl_value_t* b) {
  return pl_val_bool((a->type != PL_VAL_NIL && (a->type != PL_VAL_BOOL || a->as.boolean)) || (b->type != PL_VAL_NIL && (b->type != PL_VAL_BOOL || b->as.boolean)));
}

pl_list_t* pl_list_from_array(pl_value_t* items, int count) {
  pl_list_t* list = pl_list_new();
  for (int i = 0; i < count; i++) {
    pl_list_push(list, items[i]);
  }
  return list;
}

pl_value_t pl_make_closure(pl_value_t (*fn)(pl_env_t*, pl_value_t*, int, pl_value_t*), pl_env_t* captured_env, int arity) {
  pl_closure_t* closure = malloc(sizeof(pl_closure_t));
  closure->fn_ptr = fn;
  closure->captured_env = captured_env;
  closure->arity = arity;
  return (pl_value_t){.type = PL_VAL_CLOSURE, .as.closure = closure};
}

pl_value_t pl_call(pl_value_t callee, pl_value_t* args, int argc) {
  switch (callee.type) {
    case PL_VAL_CLOSURE: {
      pl_closure_t* closure = callee.as.closure;
      pl_env_t* call_env = pl_env_new();
      if (closure->captured_env) {
        pl_env_frame_t* frame = closure->captured_env->current;
        while (frame) {
          for (int i = 0; i < frame->count; i++) {
            pl_env_define(call_env, frame->keys[i], *frame->values[i]);
          }
          frame = frame->parent;
        }
      }
      for (int i = 0; i < argc; i++) {
        pl_env_define(call_env, "arg", args[i]);
      }
      pl_value_t retval = pl_val_nil();
      closure->fn_ptr(call_env, args, argc, &retval);
      return retval;
      }
      case PL_VAL_NATIVE_FN: {
        pl_value_t (*fn)(pl_env_t*, pl_value_t*, int) = (pl_value_t (*)(pl_env_t*, pl_value_t*, int))callee.as.native_fn;
        return fn(pl_env_new(), args, argc);
      }
    }
    return pl_val_nil();
  }
  
  static inline pl_value_t __pl_call_args(int argc, pl_value_t callee, ...) {
    va_list va;
    va_start(va, callee);
    pl_value_t* args = malloc(argc * sizeof(pl_value_t));
    for (int i = 0; i < argc; i++) {
      args[i] = va_arg(va, pl_value_t);
    }
    va_end(va);
    pl_value_t ret = pl_call(callee, args, argc);
    free(args);
    return ret;
  }
  
  static inline pl_value_t pl_call_with_args(pl_value_t callee, pl_value_t* args, int argc) {
    return pl_call(callee, args, argc);
  }
  
int main(int argc, char** argv) {
  pl_env_t* env = pl_env_new();
  pl_env_define_native(env, "print", pl_print_value);
  pl_env_define_native(env, "file_write", pl_file_write);
  pl_env_define_native(env, "file_read", pl_file_read);
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_1));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_2));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_24));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_4));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_5));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_6));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_7));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_8));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_9));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_10));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_11));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_24));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_13));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_24));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_15));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_16));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_17));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_18));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_24));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_20));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_21));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_22));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_23));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_24));
  __pl_call_args(1, *pl_env_lookup(env, "print"), pl_val_str(__pl_str_25));
  return 0;
}