Feature: materializing a solution set within a bounded range, and the numeric fallback for equations with no closed form (sym_materialize, sym_solve_for, self_hosting/lib/symbolic.patlang -- NOT YET IMPLEMENTED, this is the pre-implementation RED spec)

  Scenario: materializing a finite Solutions set filters to the requested range
    Given the quadratic Solutions([-1.41..., 1.41...]) from x^2-2=0
    When sym_materialize is called with range Interval(0, 10)
    Then the result is a list with exactly 1 element -- only the positive root falls inside [0,10]

  Scenario: materializing an unbounded trig Family requires a range, and returns only the members inside it
    Given the sin(x)=0 Family from symbolic_periodic_solve.feature
    When sym_materialize is called with range Interval(-1, 7) -- roughly -0.3*pi to 2.2*pi
    Then the result is a list with exactly 3 elements: 0, pi, 2*pi -- generated by walking n outward
    from 0 in both directions until the generator's value leaves the range on each side, not by
    attempting to enumerate all of Z first

  Scenario: an equation with no recognized closed form requires an explicit range, unlike the closed-form cases
    Given sym_solve_for is called on sym_add(sym_var("x"), sym_sin(sym_var("x"))) for variable "x" --
    x + sin(x) = 0, which has no elementary closed form
    When called WITHOUT a bounded range
    Then it is an error -- the numeric fallback has no formula to fall back on for "all" solutions, so
    a domain is mandatory here even though it is optional for the closed-form cases (a closed-form
    result can always be materialized against a range afterward, on demand; a numeric result has no
    "afterward" -- the range has to be known before the search can even start)

  Scenario: the numeric fallback finds each root by splitting at non-monotonic points and bisecting each monotonic piece
    Given the same x + sin(x) = 0 equation, called WITH range Interval(-10, 10)
    Then the result is Solutions([...]) containing exactly 1 element, a one-ULP-wide Interval
    bracketing 0 -- x=0 is the only real root of x+sin(x) in that range, found by the solver splitting
    the range at points where sym_is_monotonic fails and bisecting each surviving monotonic piece, not
    asserted from prior knowledge of the equation

  Note: this is the one solver path where the returned Solutions list is populated by genuine numeric
  bisection rather than an exact formula -- each element is an Interval (a bracket), not a Const,
  mirroring the distinction interval-arithmetic.html already draws between Newton-Raphson's bare float
  and bisection's rigorous bracket. A caller that needs to tell "closed-form exact" apart from "numeric
  bracket" results can check whether a given Solutions element is a Const or an Interval -- the two
  closed-form features (symbolic_closed_form_solve.feature, symbolic_periodic_solve.feature) never
  produce a bare Interval element inside a Solutions list; only this numeric fallback does.
