# frozen_string_literal: true

# PatLang C Code Generator
# Translates PatLang AST to C99 code for compilation with clang

module Patlang
  module Codegen
    module CGenerator
      INDENT = "  "
      
      class CGenerator
        def initialize(options = {})
          @options = {
            target: options[:target] || 'win64',
            optimize: options[:optimize] || false,
            debug: options[:debug] || false,
            output_file: options[:output_file]
          }
          @output = []
          @indent_level = 0
          @function_count = 0
          @string_literals = {}
          @string_counter = 0
          @type_defs_emitted = false
          @function_defs = []
        end
        
        def generate(ast)
          emit_header
          emit_type_definitions
          emit_string_literals(ast)
          emit_runtime_functions
          emit_program(ast)
          @output.join("\n")
        end
        
        private
        
        def emit(line = "")
          @output << (INDENT * @indent_level) + line
        end
        
        def indent(&block)
          @indent_level += 1
          block.call
          @indent_level -= 1
        end
        
        def emit_header
          emit "// PatLang compiled output"
          emit "// Generated by PatLang C Code Generator"
          emit "#include <stdio.h>"
          emit "#include <stdlib.h>"
          emit "#include <string.h>"
          emit "#include <stdbool.h>"
          emit "#include <stdint.h>"
          emit "#include <math.h>"
          emit "#include <stdarg.h>"
          emit ""
        end
        
        def emit_type_definitions
          return if @type_defs_emitted
          
          emit "// ====================================================================="
          emit "// PatLang Type Definitions"
          emit "// ====================================================================="
          emit ""
          
          # Forward declare all structs
          emit "struct pl_env_frame;"
          emit "struct pl_env;"
          emit "struct pl_closure;"
          emit "struct pl_list;"
          emit "struct pl_object;"
          emit "struct pl_value;"
          emit ""
          
          # Create typedefs immediately so they can be used in pl_value_t
          emit "typedef struct pl_env_frame pl_env_frame_t;"
          emit "typedef struct pl_env pl_env_t;"
          emit "typedef struct pl_closure pl_closure_t;"
          emit "typedef struct pl_list pl_list_t;"
          emit "typedef struct pl_object pl_object_t;"
          emit "typedef struct pl_value pl_value_t;"
          emit ""
          
          # Value type tag
          emit "typedef enum {"
          indent do
            emit "PL_VAL_NIL,"
            emit "PL_VAL_BOOL,"
            emit "PL_VAL_INT,"
            emit "PL_VAL_FLOAT,"
            emit "PL_VAL_STRING,"
            emit "PL_VAL_LIST,"
            emit "PL_VAL_OBJECT,"
            emit "PL_VAL_CLOSURE,"
            emit "PL_VAL_NATIVE_FN"
          end
          emit "} pl_value_type_t;"
          emit ""
          
          # Define pl_value_t FULLY using the typedefs
          emit "typedef struct pl_value {"
          indent do
            emit "pl_value_type_t type;"
            emit "union {"
            indent do
              emit "bool boolean;"
              emit "int64_t integer;"
              emit "double floating;"
              emit "char* string;"
              emit "pl_list_t* list;"
              emit "pl_object_t* object;"
              emit "pl_closure_t* closure;"
              emit "void (*native_fn)(pl_env_t*, pl_value_t*, int, pl_value_t*);"
            end
            emit "} as;"
          end
          emit "} pl_value_t;"
          emit ""
          
          # Now define all the other structs completely
          emit "typedef struct pl_env_frame {"
          indent do
            emit "char** keys;"
            emit "pl_value_t** values;"
            emit "int count;"
            emit "int capacity;"
            emit "struct pl_env_frame* parent;"
          end
          emit "} pl_env_frame_t;"
          emit ""
          
          emit "typedef struct pl_env {"
          indent do
            emit "struct pl_env_frame* current;"
          end
          emit "} pl_env_t;"
          emit ""
          
          emit "typedef struct pl_closure {"
          indent do
            emit "pl_value_t (*fn_ptr)(pl_env_t*, pl_value_t*, int, pl_value_t*);"
            emit "struct pl_env* captured_env;"
            emit "int arity;"
          end
          emit "} pl_closure_t;"
          emit ""
          
          emit "typedef struct pl_list {"
          indent do
            emit "pl_value_t* items;"
            emit "int count;"
            emit "int capacity;"
          end
          emit "} pl_list_t;"
          emit ""
          
          emit "typedef struct pl_object_entry {"
          indent do
            emit "char* key;"
            emit "pl_value_t* value;"
          end
          emit "} pl_object_entry_t;"
          
          emit "typedef struct pl_object {"
          indent do
            emit "pl_object_entry_t* entries;"
            emit "int count;"
            emit "int capacity;"
          end
          emit "} pl_object_t;"
          emit ""
          
          emit "typedef pl_value_t (*pl_native_fn_t)(pl_env_t*, pl_value_t*, int);"
          emit ""
          
          @type_defs_emitted = true
        end
        
        def emit_string_literals(ast)
          collect_strings(ast)
          return if @string_literals.empty?
          
          emit "// String literals"
          @string_literals.each do |str, name|
            escaped = str.gsub('\\', '\\\\').gsub('"', '\\"').gsub("\n", "\\n").gsub("\r", "\\r").gsub("\t", "\\t")
            emit "static const char #{name}[] = \"#{escaped}\";"
          end
          emit ""
        end
        
        def collect_strings(node)
          case node
          when Patlang::AST::StringLiteralNode
            @string_counter += 1
            name = "__pl_str_#{@string_counter}"
            @string_literals[node.value] = name
          when Patlang::AST::ProgramNode
            node.statements.each { |s| collect_strings(s) }
          when Patlang::AST::BlockNode
            node.statements.each { |s| collect_strings(s) }
          when Patlang::AST::ExpressionStatementNode
            collect_strings(node.expression)
          when Patlang::AST::BinaryOpNode
            collect_strings(node.left)
            collect_strings(node.right)
          when Patlang::AST::CallNode
            collect_strings(node.callee)
            node.arguments.each { |a| collect_strings(a) }
          when Patlang::AST::LambdaNode
            if node.body.is_a?(Patlang::AST::BlockNode)
              node.body.statements.each { |s| collect_strings(s) }
            else
              collect_strings(node.body)
            end
          when Patlang::AST::IfStatementNode
            collect_strings(node.condition)
            collect_strings(node.then_branch)
            node.elsif_branches.each { |c, b| collect_strings(c); collect_strings(b) }
            collect_strings(node.else_branch) if node.else_branch
          when Patlang::AST::FunctionDeclarationNode
            if node.body.is_a?(Patlang::AST::BlockNode)
              node.body.statements.each { |s| collect_strings(s) }
            end
          when Patlang::AST::ReturnStatementNode
            collect_strings(node.value) if node.value
          when Patlang::AST::ListLiteralNode
            node.elements.each { |e| collect_strings(e) }
          when Patlang::AST::ObjectLiteralNode
            node.pairs.each { |p| collect_strings(p.value) }
          when Patlang::AST::VariableDeclarationNode
            collect_strings(node.initializer) if node.initializer
          when Patlang::AST::AssignmentNode
            collect_strings(node.value)
          when Patlang::AST::MutationNode
            collect_strings(node.value)
          end
        end
        
        def emit_runtime_functions
          emit "// ====================================================================="
          emit "// Runtime Functions"
          emit "// ====================================================================="
          emit ""
          
          emit "pl_env_t* pl_env_new() {"
          indent do
            emit "pl_env_t* env = malloc(sizeof(pl_env_t));"
            emit "env->current = NULL;"
            emit "return env;"
          end
          emit "}"
          emit ""
          
          emit "void pl_env_push_frame(pl_env_t* env) {"
          indent do
            emit "pl_env_frame_t* frame = malloc(sizeof(pl_env_frame_t));"
            emit "frame->keys = NULL;"
            emit "frame->values = NULL;"
            emit "frame->count = 0;"
            emit "frame->capacity = 0;"
            emit "frame->parent = env->current;"
            emit "env->current = frame;"
          end
          emit "}"
          emit ""
          
          emit "void pl_env_pop_frame(pl_env_t* env) {"
          indent do
            emit "if (env->current) {"
            indent do
              emit "pl_env_frame_t* frame = env->current;"
              emit "env->current = frame->parent;"
              emit "free(frame->keys);"
              emit "free(frame->values);"
              emit "free(frame);"
            end
            emit "}"
          end
          emit "}"
          emit ""
          
          emit "void pl_env_define(pl_env_t* env, const char* name, pl_value_t value) {"
          indent do
            emit "if (!env->current) pl_env_push_frame(env);"
            emit "pl_env_frame_t* frame = env->current;"
            emit "// Check if variable exists in current frame (for assignment/update)"
            emit "for (int i = 0; i < frame->count; i++) {"
            indent do
              emit "if (strcmp(frame->keys[i], name) == 0) {"
              indent do
                emit "*frame->values[i] = value;"
                emit "return;"
              end
              emit "}"
            end
            emit "}"
            emit "// Not found, add new binding"
            emit "if (frame->count >= frame->capacity) {"
            indent do
              emit "int new_cap = frame->capacity ? frame->capacity * 2 : 8;"
              emit "frame->keys = realloc(frame->keys, new_cap * sizeof(char*));"
              emit "frame->values = realloc(frame->values, new_cap * sizeof(pl_value_t*));"
              emit "frame->capacity = new_cap;"
            end
            emit "}"
            emit "frame->keys[frame->count] = strdup(name);"
            emit "frame->values[frame->count] = malloc(sizeof(pl_value_t));"
            emit "*frame->values[frame->count] = value;"
            emit "frame->count++;"
          end
          emit "}"
          emit ""
          
          emit "void pl_env_define_native(pl_env_t* env, const char* name, pl_value_t (*fn)(pl_env_t*, pl_value_t*, int, pl_value_t*)) {"
          indent do
            emit "if (!env->current) pl_env_push_frame(env);"
            emit "pl_env_frame_t* frame = env->current;"
            emit "if (frame->count >= frame->capacity) {"
            indent do
              emit "int new_cap = frame->capacity ? frame->capacity * 2 : 8;"
              emit "frame->keys = realloc(frame->keys, new_cap * sizeof(char*));"
              emit "frame->values = realloc(frame->values, new_cap * sizeof(pl_value_t*));"
              emit "frame->capacity = new_cap;"
            end
            emit "}"
            emit "frame->keys[frame->count] = strdup(name);"
            emit "pl_closure_t* closure = malloc(sizeof(pl_closure_t));"
            emit "closure->fn_ptr = fn;"
            emit "closure->captured_env = NULL;"
            emit "closure->arity = -1;"
            emit "frame->values[frame->count] = malloc(sizeof(pl_value_t));"
            emit "*frame->values[frame->count] = (pl_value_t){.type = PL_VAL_CLOSURE, .as.closure = closure};"
            emit "frame->count++;"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t* pl_env_lookup(pl_env_t* env, const char* name) {"
          indent do
            emit "pl_env_frame_t* frame = env->current;"
            emit "while (frame) {"
            indent do
              emit "for (int i = 0; i < frame->count; i++) {"
              indent do
                emit "if (strcmp(frame->keys[i], name) == 0) {"
                indent do
                  emit "return frame->values[i];"
                end
                emit "}"
              end
              emit "}"
              emit "frame = frame->parent;"
            end
            emit "}"
            emit "return NULL;"
          end
          emit "}"
          emit ""
          
          emit "void pl_env_assign(pl_env_t* env, const char* name, pl_value_t value) {"
          indent do
            emit "pl_env_frame_t* frame = env->current;"
            emit "while (frame) {"
            indent do
              emit "for (int i = 0; i < frame->count; i++) {"
              indent do
                emit "if (strcmp(frame->keys[i], name) == 0) {"
                indent do
                  emit "*frame->values[i] = value;"
                  emit "return;"
                end
                emit "}"
              end
              emit "}"
              emit "frame = frame->parent;"
            end
            emit "}"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_val_nil() { return (pl_value_t){.type = PL_VAL_NIL}; }"
          emit "pl_value_t pl_val_bool(bool b) { return (pl_value_t){.type = PL_VAL_BOOL, .as.boolean = b}; }"
          emit "pl_value_t pl_val_int(int64_t i) { return (pl_value_t){.type = PL_VAL_INT, .as.integer = i}; }"
          emit "pl_value_t pl_val_float(double f) { return (pl_value_t){.type = PL_VAL_FLOAT, .as.floating = f}; }"
          emit "pl_value_t pl_val_str(const char* s) { return (pl_value_t){.type = PL_VAL_STRING, .as.string = strdup(s)}; }"
          emit ""
          
          emit "pl_list_t* pl_list_new() {"
          indent do
            emit "pl_list_t* list = malloc(sizeof(pl_list_t));"
            emit "list->items = NULL;"
            emit "list->count = 0;"
            emit "list->capacity = 0;"
            emit "return list;"
          end
          emit "}"
          emit ""
          
          emit "void pl_list_push(pl_list_t* list, pl_value_t value) {"
          indent do
            emit "if (list->count >= list->capacity) {"
            indent do
              emit "int new_cap = list->capacity ? list->capacity * 2 : 8;"
              emit "list->items = realloc(list->items, new_cap * sizeof(pl_value_t));"
              emit "list->capacity = new_cap;"
            end
            emit "}"
            emit "list->items[list->count++] = value;"
          end
          emit "}"
          emit ""
          
          emit "bool pl_is_truthy(pl_value_t v) {"
          indent do
            emit "switch (v.type) {"
            indent do
              emit "case PL_VAL_NIL: return false;"
              emit "case PL_VAL_BOOL: return v.as.boolean;"
              emit "default: return true;"
            end
            emit "}"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_print_value(pl_env_t* env, pl_value_t* args, int argc, pl_value_t* retval) {"
          indent do
            emit "for (int i = 0; i < argc; i++) {"
            indent do
              emit "pl_value_t v = args[i];"
              emit "switch (v.type) {"
              indent do
                emit "case PL_VAL_NIL: printf(\"nil\"); break;"
                emit "case PL_VAL_BOOL: printf(v.as.boolean ? \"true\" : \"false\"); break;"
                emit "case PL_VAL_INT: printf(\"%lld\", (long long)v.as.integer); break;"
                emit "case PL_VAL_FLOAT: printf(\"%g\", v.as.floating); break;"
                emit "case PL_VAL_STRING: printf(\"%s\", v.as.string); break;"
                emit "case PL_VAL_LIST: {"
                indent do
                  emit "printf(\"[\");"
                  emit "for (int j = 0; j < v.as.list->count; j++) {"
                  indent do
                    emit "if (j > 0) printf(\", \");"
                    # Inline the print logic for list elements instead of recursive call
                    emit "pl_value_t elem = v.as.list->items[j];"
                    emit "switch (elem.type) {"
                    indent do
                      emit "case PL_VAL_NIL: printf(\"nil\"); break;"
                      emit "case PL_VAL_BOOL: printf(elem.as.boolean ? \"true\" : \"false\"); break;"
                      emit "case PL_VAL_INT: printf(\"%lld\", (long long)elem.as.integer); break;"
                      emit "case PL_VAL_FLOAT: printf(\"%g\", elem.as.floating); break;"
                      emit "case PL_VAL_STRING: printf(\"%s\", elem.as.string); break;"
                      emit "case PL_VAL_LIST: printf(\"<list>\"); break;"
                      emit "default: printf(\"<value>\"); break;"
                    end
                    emit "}"
                  end
                  emit "}"
                  emit "printf(\"]\");"
                end
                emit "} break;"
                emit "default: printf(\"<value>\"); break;"
              end
              emit "}"
            end
            emit "}"
            emit "if (argc > 0) {"
            indent { emit "*retval = args[argc - 1];" }
            emit "} else {"
            indent { emit "*retval = pl_val_nil();" }
            emit "}"
            emit "return *retval;"
          end
          emit "}"
          emit ""
          
          # File I/O functions
          emit "pl_value_t pl_file_write(pl_env_t* env, pl_value_t* args, int argc, pl_value_t* retval) {"
          indent do
            emit "if (argc < 2) { *retval = pl_val_nil(); return *retval; }"
            emit "pl_value_t* filename_val = &args[0];"
            emit "pl_value_t* content_val = &args[1];"
            emit "if (filename_val->type != PL_VAL_STRING || content_val->type != PL_VAL_STRING) {"
            indent { emit "*retval = pl_val_nil(); return *retval;" }
            emit "}"
            emit "FILE* f = fopen(filename_val->as.string, \"a\");"
            emit "if (!f) { *retval = pl_val_nil(); return *retval; }"
            emit "fwrite(content_val->as.string, 1, strlen(content_val->as.string), f);"
            emit "fclose(f);"
            emit "*retval = pl_val_bool(true);"
            emit "return *retval;"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_file_read(pl_env_t* env, pl_value_t* args, int argc, pl_value_t* retval) {"
          indent do
            emit "if (argc < 1) { *retval = pl_val_nil(); return *retval; }"
            emit "pl_value_t* filename_val = &args[0];"
            emit "if (filename_val->type != PL_VAL_STRING) {"
            indent { emit "*retval = pl_val_nil(); return *retval;" }
            emit "}"
            emit "FILE* f = fopen(filename_val->as.string, \"r\");"
            emit "if (!f) { *retval = pl_val_nil(); return *retval; }"
            emit "fseek(f, 0, SEEK_END);"
            emit "long len = ftell(f);"
            emit "fseek(f, 0, SEEK_SET);"
            emit "char* buf = malloc(len + 1);"
            emit "fread(buf, 1, len, f);"
            emit "buf[len] = '\\0';"
            emit "fclose(f);"
            emit "pl_value_t result = pl_val_str(buf);"
            emit "free(buf);"
            emit "*retval = result;"
            emit "return *retval;"
          end
          emit "}"
          emit ""
          
          # Binary operations (accept pointers since environment stores pointers)
          emit "pl_value_t pl_add(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_int(a->as.integer + b->as.integer);"
            emit "if (a->type == PL_VAL_FLOAT && b->type == PL_VAL_FLOAT) return pl_val_float(a->as.floating + b->as.floating);"
            emit "if (a->type == PL_VAL_INT && b->type == PL_VAL_FLOAT) return pl_val_float(a->as.integer + b->as.floating);"
            emit "if (a->type == PL_VAL_FLOAT && b->type == PL_VAL_INT) return pl_val_float(a->as.floating + b->as.integer);"
            emit "return pl_val_nil();"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_sub(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_int(a->as.integer - b->as.integer);"
            emit "if (a->type == PL_VAL_FLOAT && b->type == PL_VAL_FLOAT) return pl_val_float(a->as.floating - b->as.floating);"
            emit "return pl_val_float((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) - (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_mul(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_int(a->as.integer * b->as.integer);"
            emit "return pl_val_float((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) * (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_div(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "return pl_val_float((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) / (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_eq(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "return pl_val_bool(a->type == b->type && ((a->type == PL_VAL_INT && a->as.integer == b->as.integer) || (a->type == PL_VAL_FLOAT && a->as.floating == b->as.floating) || (a->type == PL_VAL_BOOL && a->as.boolean == b->as.boolean) || (a->type == PL_VAL_STRING && strcmp(a->as.string, b->as.string) == 0)));"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_ne(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "return pl_val_bool(!(a->type == b->type && ((a->type == PL_VAL_INT && a->as.integer == b->as.integer) || (a->type == PL_VAL_FLOAT && a->as.floating == b->as.floating) || (a->type == PL_VAL_BOOL && a->as.boolean == b->as.boolean) || (a->type == PL_VAL_STRING && strcmp(a->as.string, b->as.string) == 0))));"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_lt(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_bool(a->as.integer < b->as.integer);"
            emit "return pl_val_bool((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) < (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_gt(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_bool(a->as.integer > b->as.integer);"
            emit "return pl_val_bool((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) > (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_le(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_bool(a->as.integer <= b->as.integer);"
            emit "return pl_val_bool((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) <= (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_ge(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "if (a->type == PL_VAL_INT && b->type == PL_VAL_INT) return pl_val_bool(a->as.integer >= b->as.integer);"
            emit "return pl_val_bool((a->type == PL_VAL_INT ? a->as.integer : a->as.floating) >= (b->type == PL_VAL_INT ? b->as.integer : b->as.floating));"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_and(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "return pl_val_bool((a->type != PL_VAL_NIL && (a->type != PL_VAL_BOOL || a->as.boolean)) && (b->type != PL_VAL_NIL && (b->type != PL_VAL_BOOL || b->as.boolean)));"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_or(pl_value_t* a, pl_value_t* b) {"
          indent do
            emit "return pl_val_bool((a->type != PL_VAL_NIL && (a->type != PL_VAL_BOOL || a->as.boolean)) || (b->type != PL_VAL_NIL && (b->type != PL_VAL_BOOL || b->as.boolean)));"
          end
          emit "}"
          emit ""
          
          # List functions
          emit "pl_list_t* pl_list_from_array(pl_value_t* items, int count) {"
          indent do
            emit "pl_list_t* list = pl_list_new();"
            emit "for (int i = 0; i < count; i++) {"
            indent { emit "pl_list_push(list, items[i]);" }
            emit "}"
            emit "return list;"
          end
          emit "}"
          emit ""
          
          # Closure/Call functions
          emit "pl_value_t pl_make_closure(pl_value_t (*fn)(pl_env_t*, pl_value_t*, int, pl_value_t*), pl_env_t* captured_env, int arity) {"
          indent do
            emit "pl_closure_t* closure = malloc(sizeof(pl_closure_t));"
            emit "closure->fn_ptr = fn;"
            emit "closure->captured_env = captured_env;"
            emit "closure->arity = arity;"
            emit "return (pl_value_t){.type = PL_VAL_CLOSURE, .as.closure = closure};"
          end
          emit "}"
          emit ""
          
          emit "pl_value_t pl_call(pl_value_t callee, pl_value_t* args, int argc) {"
          indent do
            emit "switch (callee.type) {"
            indent do
              emit "case PL_VAL_CLOSURE: {"
              indent do
                emit "pl_closure_t* closure = callee.as.closure;"
                emit "pl_env_t* call_env = pl_env_new();"
                emit "if (closure->captured_env) {"
                indent do
                  emit "pl_env_frame_t* frame = closure->captured_env->current;"
                  emit "while (frame) {"
                  indent do
                    emit "for (int i = 0; i < frame->count; i++) {"
                    indent { emit "pl_env_define(call_env, frame->keys[i], *frame->values[i]);" }
                    emit "}"
                    emit "frame = frame->parent;"
                  end
                  emit "}"
                end
                emit "}"
                emit "for (int i = 0; i < argc; i++) {"
                indent { emit "pl_env_define(call_env, \"arg\", args[i]);" }
                emit "}"
                emit "pl_value_t retval = pl_val_nil();"
                emit "closure->fn_ptr(call_env, args, argc, &retval);"
                emit "return retval;"
                emit "}"
                emit "case PL_VAL_NATIVE_FN: {"
                indent do
                  emit "pl_value_t (*fn)(pl_env_t*, pl_value_t*, int) = (pl_value_t (*)(pl_env_t*, pl_value_t*, int))callee.as.native_fn;"
                  emit "return fn(pl_env_new(), args, argc);"
                end
                emit "}"
              end
              emit "}"
              emit "return pl_val_nil();"
            end
            emit "}"
            emit ""
            
            # Helper for calling functions with variable args - variadic avoids compound literal issues
            emit "static inline pl_value_t __pl_call_args(int argc, pl_value_t callee, ...) {"
            indent do
              emit "va_list va;"
              emit "va_start(va, callee);"
              emit "pl_value_t* args = malloc(argc * sizeof(pl_value_t));"
              emit "for (int i = 0; i < argc; i++) {"
              indent { emit "args[i] = va_arg(va, pl_value_t);" }
              emit "}"
              emit "va_end(va);"
              emit "pl_value_t ret = pl_call(callee, args, argc);"
              emit "free(args);"
              emit "return ret;"
            end
            emit "}"
            emit ""
            
            # Helper for calling functions with variable args (defined AFTER pl_call)
            emit "static inline pl_value_t pl_call_with_args(pl_value_t callee, pl_value_t* args, int argc) {"
            indent do
              emit "return pl_call(callee, args, argc);"
            end
            emit "}"
            emit ""
        end
        
        def emit_program(ast)
          case ast
          when Patlang::AST::ProgramNode
            # First pass: collect all function definitions from statements
            ast.statements.each { |stmt| collect_function_defs(stmt) }
            
            # Emit collected function definitions at global scope
            unless @function_defs.empty?
              @function_defs.each do |node|
                fname = "pl_fn_#{node.name}"
                # Function with proper signature
                emit "pl_value_t #{fname}(pl_env_t* env, pl_value_t* args, int argc, pl_value_t* retval) {"
                indent do
                  emit "pl_env_push_frame(env);"
                  node.parameters.each_with_index do |param, i|
                    emit "pl_env_define(env, \"#{param.name}\", argc > #{i} ? args[#{i}] : pl_val_nil());"
                  end
                  if node.body.is_a?(Patlang::AST::BlockNode)
                    node.body.statements.each { |stmt| emit_statement(stmt, "env") }
                  else
                    emit "// single expr body"
                  end
                  # Return void/nil for the function
                  emit "return pl_val_nil();"
                  emit "pl_env_pop_frame(env);"
                end
                emit "}"
                emit ""
              end
            end
            
            # Main function
            emit "int main(int argc, char** argv) {"
            indent do
              emit "pl_env_t* env = pl_env_new();"
              emit "pl_env_define_native(env, \"print\", pl_print_value);"
              emit "pl_env_define_native(env, \"file_write\", pl_file_write);"
              emit "pl_env_define_native(env, \"file_read\", pl_file_read);"
              ast.statements.each { |stmt| emit_statement(stmt, "env") }
              emit "return 0;"
            end
            emit "}"
          else
            emit_statement(ast, "env")
          end
        end
        
        def collect_function_defs(node)
          return unless node
          if node.is_a?(Patlang::AST::FunctionDeclarationNode)
            @function_defs << node
          end
          # Recurse into blocks
          if node.respond_to?(:statements)
            node.statements.each { |s| collect_function_defs(s) }
          end
          if node.respond_to?(:then_branch)
            collect_function_defs(node.then_branch)
          end
          if node.respond_to?(:else_branch)
            collect_function_defs(node.else_branch)
          end
          node.elsif_branches.each { |_, b| collect_function_defs(b) } if node.respond_to?(:elsif_branches)
          if node.respond_to?(:body)
            collect_function_defs(node.body)
          end
        end
        
        def emit_statement(node, env_var)
          return if node.nil?
          
          case node
          when Patlang::AST::ExpressionStatementNode
            expr_code = emit_expression(node.expression, env_var)
            emit "#{expr_code};"
          when Patlang::AST::VariableDeclarationNode
            emit_var_decl(node, env_var)
          when Patlang::AST::AssignmentNode
            emit_assignment(node, env_var)
          when Patlang::AST::MutationNode
            emit_mutation(node, env_var)
          when Patlang::AST::IfStatementNode
            emit_if(node, env_var)
          when Patlang::AST::WhileStatementNode
            emit_while(node, env_var)
          when Patlang::AST::ForStatementNode
            emit_for(node, env_var)
          when Patlang::AST::ReturnStatementNode
            emit_return(node, env_var)
          when Patlang::AST::FunctionDeclarationNode
            emit_function_decl(node, env_var)
          else
            emit "// Unknown statement: #{node.class}"
          end
        end
        
        def emit_expression(node, env_var)
          return "pl_val_nil()" if node.nil?
          
          case node
          when Patlang::AST::IntegerLiteralNode
            "pl_val_int(#{node.value})"
          when Patlang::AST::FloatLiteralNode
            "pl_val_float(#{node.value})"
          when Patlang::AST::StringLiteralNode
            name = @string_literals[node.value]
            "pl_val_str(#{name})"
          when Patlang::AST::BooleanLiteralNode
            "pl_val_bool(#{node.value ? 'true' : 'false'})"
          when Patlang::AST::NilLiteralNode
            "pl_val_nil()"
          when Patlang::AST::IdentifierNode
            "pl_env_lookup(#{env_var}, \"#{node.name}\")"
          when Patlang::AST::BinaryOpNode
            left = emit_expression(node.left, env_var)
            right = emit_expression(node.right, env_var)
            op = case node.operator
            when "+" then "pl_add"
            when "-" then "pl_sub"
            when "*" then "pl_mul"
            when "/" then "pl_div"
            when "=" then "pl_eq"
            when "!=" then "pl_ne"
            when "<" then "pl_lt"
            when ">" then "pl_gt"
            when "<=" then "pl_le"
            when ">=" then "pl_ge"
            when "and" then "pl_and"
            when "or" then "pl_or"
            else "pl_add"
            end
            # For all binary ops, if right is a literal value, need temporary variable
            if right.start_with?("pl_val_")
              "({ pl_value_t __tmp = #{right}; #{op}(#{left}, &__tmp); })"
            else
              "#{op}(#{left}, #{right})"
            end
          when Patlang::AST::CallNode
            emit_call(node, env_var)
          when Patlang::AST::LambdaNode
            "// lambda #{emit_lambda(node, env_var)}"
          when Patlang::AST::ListLiteralNode
            items = node.elements.map { |e| emit_expression(e, env_var) }.join(", ")
            "pl_list_from_array((pl_value_t[]){#{items}}, #{node.elements.count})"
          when Patlang::AST::ObjectLiteralNode
            "// object literal pl_val_nil()"
          else
            "// #{node.class} pl_val_nil()"
          end
        end
        
        def emit_call(node, env_var)
          callee = emit_expression(node.callee, env_var)
          if node.arguments.empty?
            "pl_call(#{callee}, NULL, 0)"
          else
            args = node.arguments.map { |a| emit_expression(a, env_var) }.join(", ")
            # Use variadic helper with argc first, then callee, then args
            "__pl_call_args(#{node.arguments.count}, *#{callee}, #{args})"
          end
        end
        
        def emit_lambda(node, env_var)
          "// lambda"
        end
        
        def emit_var_decl(node, env_var)
          init = node.initializer ? emit_expression(node.initializer, env_var) : "pl_val_nil()"
          emit "pl_env_define(#{env_var}, \"#{node.name}\", #{init});"
        end
        
        def emit_assignment(node, env_var)
          val = emit_expression(node.value, env_var)
          emit "pl_env_define(#{env_var}, \"#{node.name}\", #{val});"
        end
        
        def emit_mutation(node, env_var)
          val = emit_expression(node.value, env_var)
          emit "pl_env_assign(#{env_var}, \"#{node.name}\", #{val});"
        end
        
        def emit_if(node, env_var)
          cond = emit_expression(node.condition, env_var)
          emit "if (pl_is_truthy(#{cond})) {"
          indent { emit_block(node.then_branch, env_var) }
          emit "}"
          node.elsif_branches.each do |cond_node, branch|
            cond = emit_expression(cond_node, env_var)
            emit "else if (pl_is_truthy(#{cond})) {"
            indent { emit_block(branch, env_var) }
            emit "}"
          end
          if node.else_branch
            emit "else {"
            indent { emit_block(node.else_branch, env_var) }
            emit "}"
          end
        end
        
        def emit_while(node, env_var)
          cond = emit_expression(node.condition, env_var)
          emit "while (pl_is_truthy(#{cond})) {"
          indent { emit_block(node.body, env_var) }
          emit "}"
        end
        
        def emit_for(node, env_var)
          emit "// for loop not fully implemented"
        end
        
        def emit_return(node, env_var)
          val = node.value ? emit_expression(node.value, env_var) : "pl_val_nil()"
          emit "*retval = #{val};"
        end
        
        def emit_function_decl(node, env_var)
          fname = "pl_fn_#{node.name}"
          # Store function definition for global emission
          @function_defs << node
          # Register the function in the environment with a forward reference
          emit "extern pl_value_t #{fname}(pl_env_t*, pl_value_t*, int, pl_value_t*);"
          emit "pl_env_define(#{env_var}, \"#{node.name}\", pl_make_closure((pl_value_t(*)(pl_env_t*, pl_value_t*, int, pl_value_t*))#{fname}, NULL, #{node.parameters.count}));"
        end
        
        def emit_call(node, env_var)
          callee = emit_expression(node.callee, env_var)
          if node.arguments.empty?
            "pl_call(#{callee}, NULL, 0)"
          else
            args = node.arguments.map { |a| emit_expression(a, env_var) }.join(", ")
            # Use variadic helper with argc first, then callee, then args
            "__pl_call_args(#{node.arguments.count}, *#{callee}, #{args})"
          end
        end
        
        def emit_block(block_node, env_var)
          return unless block_node
          block_node.statements.each { |stmt| emit_statement(stmt, env_var) }
        end
      end
    end
  end
end
end