#!/usr/bin/env ruby
# Auto-generated by PatLang's self-hosted Ruby transpiler
# (self_hosting/lib/transpile_ruby.patlang). Do not edit by hand.
require_relative "patlang_runtime"

def fib(n)
  if (n < 2)
    return n
  else
    return (fib((n - 1)) + fib((n - 2)))
  end
end
i = 0
while (i < 6)
  puts(PL.display(fib(i)))
  i = (i + 1)
end
puts(PL.display(PL.div(10, 3)))
puts(PL.display(PL.sqrt((-4))))
PL.new_obj("Counter", "c1")
PL.send_obj("c1", "set", "v", 5)
puts(PL.display(PL.get_obj("c1", "v")))
