// Auto-generated by patlang IR->Rust codegen (Stage 0)
#![allow(dead_code, unused_imports, unused_variables, unused_mut)]
// Standalone runtime + embedded program


use std::collections::HashMap;
use std::cell::RefCell;

thread_local! {
    static OBJECTS: RefCell<HashMap<String, HashMap<String, Value>>> = RefCell::new(HashMap::new());
    static FACTS: RefCell<HashMap<String, Vec<(String, String)>>> = RefCell::new(HashMap::new());
    static GOALS: RefCell<Vec<(String, Vec<String>)>> = RefCell::new(Vec::new());
    static TYPE_RULES: RefCell<HashMap<(String, usize), String>> = RefCell::new(HashMap::new());
    static EVENT_HANDLERS: RefCell<HashMap<String, Vec<String>>> = RefCell::new(HashMap::new());
    static LISTENERS: RefCell<HashMap<u16, std::net::TcpListener>> = RefCell::new(HashMap::new());
    static CONNS: RefCell<HashMap<usize, std::net::TcpStream>> = RefCell::new(HashMap::new());
    static NEXT_CONN: RefCell<usize> = RefCell::new(1);
    static VECS: RefCell<Vec<Vec<Value>>> = RefCell::new(Vec::new());
    static SBUFS: RefCell<Vec<String>> = RefCell::new(Vec::new());
    static ISTRINGS: RefCell<Vec<String>> = RefCell::new(Vec::new());
}

fn arg_usize(args: &[Value], i: usize, what: &str) -> Result<usize, String> {
    match args.get(i) {
        Some(Value::Number(n)) => Ok(*n as usize),
        Some(Value::String(s)) => s.trim().parse::<usize>().map_err(|_| format!("{}: expected index", what)),
        _ => Err(format!("{}: expected number", what)),
    }
}

fn arg_num(args: &[Value], i: usize, what: &str) -> Result<f64, String> {
    match args.get(i) {
        Some(Value::Number(n)) => Ok(*n),
        Some(Value::String(s)) => s.trim().parse::<f64>().map_err(|_| format!("{}: expected number", what)),
        _ => Err(format!("{}: expected number", what)),
    }
}

fn obj_get(name: &str, prop: &str) -> Option<Value> {
    OBJECTS.with(|o| {
        let b = o.borrow();
        b.get(name).and_then(|m| m.get(prop)).cloned()
    })
}

fn obj_set(name: &str, prop: &str, val: Value) {
    OBJECTS.with(|o| {
        let mut b = o.borrow_mut();
        let m = b.entry(name.to_string()).or_insert_with(HashMap::new);
        m.insert(prop.to_string(), val);
    });
}

fn ensure_obj(name: &str, class: &str) {
    obj_set(name, "type", Value::String(class.to_string()));
    obj_set(name, "name", Value::String(name.to_string()));
}

fn log_to_file(filename: &str, msg: &str) {
    use std::io::Write;
    if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open(filename) {
        let _ = writeln!(f, "{}", msg);
    }
}

fn create_temp_file(name: &str) -> Result<String, String> {
    let mut dir = std::env::temp_dir();
    dir.push("patlang_native");
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let path = dir.join(name);
    std::fs::File::create(&path).map_err(|e| e.to_string())?;
    Ok(path.display().to_string())
}

fn write_to_file(path: &str, content: &str) -> Result<(), String> {
    std::fs::write(path, content).map_err(|e| e.to_string())
}

fn move_or_copy(src: &str, dest: &str) -> Result<(), String> {
    if let Some(parent) = std::path::Path::new(dest).parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    match std::fs::rename(src, dest) {
        Ok(_) => Ok(()),
        Err(_) => std::fs::copy(src, dest).map(|_| ()).map_err(|e| e.to_string()),
    }
}

fn file_exists(path: &str) -> bool {
    std::path::Path::new(path).exists()
}

#[derive(Clone, Debug, PartialEq)]
enum Value {
    Unit,
    Bool(bool),
    Number(f64),
    String(String),
    List(Vec<Value>),
    Object(HashMap<String, Value>),
    Closure { func_name: String, captured: Vec<(String, Value)> },
}

impl Value {
    fn as_number(&self) -> Result<f64, String> {
        match self {
            Value::Number(n) => Ok(*n),
            Value::Unit => Ok(0.0),
            _ => Err("expected number".into()),
        }
    }
    fn as_bool(&self) -> Result<bool, String> {
        match self {
            Value::Bool(b) => Ok(*b),
            Value::Unit => Ok(false),
            Value::Number(n) => Ok(*n != 0.0),
            Value::String(s) => Ok(!s.is_empty()),
            Value::List(xs) => Ok(!xs.is_empty()),
            Value::Object(map) => Ok(!map.is_empty()),
            Value::Closure { .. } => Ok(true),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
enum BinOpKind { Add, Sub, Mul, Div, Mod, Eq, Ne, Lt, Le, Gt, Ge, And, Or }
#[derive(Clone, Debug, PartialEq)]
enum UnOpKind { Neg, Not }

#[derive(Clone, Debug, PartialEq)]
enum Instr {
    Const(Value),
    LoadLocal(String),
    StoreLocal(String),
    BinOp(BinOpKind),
    UnOp(UnOpKind),
    Jump(usize),
    JumpIfFalse(usize),
    CallHost(String, usize),
    Call(String, usize),
    MakeClosure(String, Vec<String>),
    CallValue(usize),
    BuildList(usize),
    Return,
}

struct Host;

impl Host {
    fn call(name: &str, args: &[Value]) -> Result<Value, String> {
        match name {
            "parse_tiny_source" => {
                // Return a lightweight Program object carrying the source path for delegation.
                // { type: "Program", source_path: <string> }
                let path = match args.get(0) { Some(Value::String(s)) => s.clone(), Some(v) => display_value(v), None => String::new() };
                let mut m = std::collections::HashMap::new();
                m.insert("type".to_string(), Value::String("Program".to_string()));
                m.insert("source_path".to_string(), Value::String(path));
                Ok(Value::Object(m))
            }
            "lower_and_compile" => {
                // Delegate compilation to the Stage 0 interpreter (pat) if available.
                // Accepts: lower_and_compile(programObj[, outPath])
                // programObj is expected to be { type: "Program", source_path: <string> } from parse_tiny_source.
                println!("[host lower_and_compile] ENTER args_len={}", args.len());
                if args.is_empty() { println!("[host lower_and_compile] no args"); return Ok(Value::String(String::new())); }
                let src_path = match &args[0] {
                    Value::Object(map) => match map.get("source_path") { Some(Value::String(s)) => s.clone(), _ => String::new() },
                    Value::String(s) => s.clone(),
                    other => display_value(other),
                };
                let out_opt = args.get(1).map(|v| match v { Value::String(s) => s.clone(), other => display_value(other) });
                println!("[host lower_and_compile] src_path={} out_opt={}", src_path, out_opt.clone().unwrap_or_default());

                // Resolve Stage 0 runner strictly from project-local paths (no PATH fallback)
                let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
                let rel_candidates = [
                    "rust-runtime/target/debug/pat",
                    "rust-runtime/target/debug/pat.exe",
                    "./rust-runtime/target/debug/pat",
                    "./rust-runtime/target/debug/pat.exe",
                    "..\\rust-runtime\\target\\debug\\pat.exe",
                    "rust-runtime\\target\\debug\\pat.exe",
                ];
                let abs_candidates: Vec<String> = rel_candidates.iter()
                    .map(|p| cwd.join(p).display().to_string())
                    .collect();
                let pat_path = abs_candidates.iter().find(|p| std::path::Path::new(p).exists()).cloned();
                let pat_path = match pat_path {
                    Some(p) => p,
                    None => {
                        return Err(format!(
                            "lower_and_compile: could not find project pat runner. Checked:\n{}",
                            abs_candidates.join("\n")
                        ));
                    }
                };
                println!("[host lower_and_compile] using pat at {}", pat_path);
                // Use raw strings, but on Windows convert MSYS-style (/e/...) to Windows (E:\...) for child rustc.
                let script_raw: &str = "./patc_native.patlang";
                let input_raw: String = src_path.clone();
                let out_raw: Option<String> = out_opt.clone();

                #[allow(unused_variables)]
                fn msys_to_win_path(p: &str) -> String {
                    #[cfg(windows)]
                    {
                        let b = p.as_bytes();
                        if b.len() >= 3 && b[0] == b'/' && b[2] == b'/' {
                            let drive = (b[1] as char).to_ascii_uppercase();
                            let rest = &p[3..];
                            let rest_bs = rest.replace('/', "\\");
                            return format!("{}:\\{}", drive, rest_bs);
                        }
                        // Otherwise, just replace forward slashes with backslashes to be safe
                        return p.replace('/', "\\");
                    }
                    #[cfg(not(windows))]
                    {
                        p.to_string()
                    }
                }

                // Make input absolute for reliability
                let input_abs = {
                    let p = std::path::Path::new(&input_raw);
                    if p.is_absolute() { p.to_path_buf() } else { std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from(".")).join(p) }
                };
                let input_arg = msys_to_win_path(&input_abs.display().to_string());
                // Normalize desired out path (if user provided a non-empty file path) to absolute
                let desired_out_abs: Option<String> = out_raw.as_ref().and_then(|s| {
                    let t = s.trim();
                    if t.is_empty() { return None; }
                    let p = std::path::Path::new(t);
                    let cwd_here = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
                    let abs = if p.is_absolute() { p.to_path_buf() } else { cwd_here.join(p) };
                    // If the path points to an existing directory or looks like a directory (trailing sep), ignore it
                    let looks_dir = t.ends_with('/') || t.ends_with('\\');
                    if abs.is_dir() || looks_dir { None } else { Some(abs.display().to_string()) }
                });

                // Build command: pat --emit-rust <input> (capture Rust source, we compile with rustc)
                let mut cmd = std::process::Command::new(&pat_path);
                if let Ok(cwd) = std::env::current_dir() { let _ = cmd.current_dir(&cwd); }
                cmd.arg("--emit-rust");
                if !input_arg.is_empty() { cmd.arg(&input_arg); }
                cmd.env_remove("RUST_LOG");
                cmd.env_remove("PATLANG_DEBUG");
                // Always print a concise debug line to aid bootstrap troubleshooting and write to a local log file
                let cwd_dbg = std::env::current_dir().ok().map(|p| p.display().to_string()).unwrap_or_default();
                println!(
                    "[host lower_and_compile] cwd={} using_pat={} cmd: pat --emit-rust {:?} {}",
                    cwd_dbg,
                    pat_path,
                    input_arg,
                    match &desired_out_abs { Some(p) => format!("(will compile to {:?})", p), None => String::from("") }
                );
                if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open("boot_host.log") {
                    use std::io::Write;
                    let _ = writeln!(
                        f,
                        "cwd={} pat={} cmd: pat --emit-rust {} {}",
                        cwd_dbg,
                        pat_path,
                        input_arg,
                        match &desired_out_abs { Some(p) => format!("(will compile to {})", p), None => String::from("(no dest)") }
                    );
                }
                println!("[host lower_and_compile] spawning child...");
                let out = cmd.output().map_err(|e| format!("lower_and_compile: failed to spawn pat: {}", e))?;
                println!("[host lower_and_compile] DONE status={} stdout_len={} stderr_len={}", out.status, out.stdout.len(), out.stderr.len());
                if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open("boot_host.log") {
                    use std::io::Write;
                    let _ = writeln!(f, "status={} stdout_len={} stderr_len={}", out.status, out.stdout.len(), out.stderr.len());
                }
                if !out.status.success() {
                    let stderr = String::from_utf8_lossy(&out.stderr).to_string();
                    return Err(format!("lower_and_compile: pat exited with {}\n{}", out.status, stderr));
                }
                // Locate the emitted Rust source file by parsing path from stdout or scanning for newest emitted_*.rs
                let out_stdout = String::from_utf8_lossy(&out.stdout).to_string();
                let out_stderr = String::from_utf8_lossy(&out.stderr).to_string();
                let combined = format!("{}\n{}", out_stdout, out_stderr);
                let mut rs_path: Option<String> = None;
                for line in combined.lines() {
                    let l = line.trim();
                    if let Some(rest) = l.strip_prefix("Wrote ") {
                        let p = rest.trim();
                        if p.ends_with(".rs") { rs_path = Some(p.to_string()); }
                    }
                }
                if rs_path.is_none() {
                    if let Ok(cwd) = std::env::current_dir() {
                        if let Ok(mut entries) = std::fs::read_dir(&cwd) {
                            let mut newest: Option<(std::time::SystemTime, String)> = None;
                            while let Some(Ok(e)) = entries.next() {
                                if let Some(name) = e.file_name().to_str() {
                                    if name.ends_with(".rs") && name.starts_with("emitted_") {
                                        if let Ok(md) = e.metadata() {
                                            if let Ok(t) = md.modified() {
                                                let path_str = e.path().display().to_string();
                                                newest = match newest {
                                                    Some((prev_t, _)) => if t > prev_t { Some((t, path_str)) } else { newest },
                                                    None => Some((t, path_str)),
                                                };
                                            }
                                        }
                                    }
                                }
                            }
                            if let Some((_, p)) = newest { rs_path = Some(p); }
                        }
                    }
                }
                let rs_path = rs_path.ok_or_else(|| format!("lower_and_compile: couldn't find emitted .rs file in pat output. output was:\n{}", combined))?;
                println!("[host lower_and_compile] will compile Rust source at {}", rs_path);
                let rust_src = std::fs::read_to_string(&rs_path).map_err(|e| format!("lower_and_compile: failed to read {}: {}", rs_path, e))?;
                if rust_src.trim().is_empty() { return Err("lower_and_compile: emitted .rs file was empty".into()); }
                // Choose destination path
                let dest_path: String = if let Some(d) = desired_out_abs { d } else {
                    let in_p = std::path::Path::new(&input_arg);
                    let stem = in_p.file_stem().and_then(|s| s.to_str()).unwrap_or("a");
                    let parent = in_p.parent().unwrap_or_else(|| std::path::Path::new("."));
                    let mut outp = parent.join(stem);
                    if cfg!(windows) { outp.set_extension("exe"); }
                    outp.display().to_string()
                };
                // Guard against Windows reserved device names
                #[cfg(windows)]
                {
                    use std::path::Path;
                    let base = Path::new(&dest_path).file_stem().and_then(|s| s.to_str()).unwrap_or("").to_ascii_uppercase();
                    let reserved = ["CON","PRN","AUX","NUL","COM1","COM2","COM3","COM4","COM5","COM6","COM7","COM8","COM9","LPT1","LPT2","LPT3","LPT4","LPT5","LPT6","LPT7","LPT8","LPT9"];
                    if reserved.contains(&base.as_str()) {
                        return Err(format!("lower_and_compile: '{}' is a reserved Windows filename; choose a different output name", base));
                    }
                }
                // Precreate the output file to test write permissions
                {
                    let dp = std::path::Path::new(&dest_path);
                    if let Some(par) = dp.parent() { let _ = std::fs::create_dir_all(par); }
                    match std::fs::OpenOptions::new().create(true).write(true).truncate(true).open(&dp) {
                        Ok(_) => {
                            println!("[host lower_and_compile] precreated output file at {}", dp.display());
                        }
                        Err(e) => {
                            println!("[host lower_and_compile] precreate failed at {}: {}", dp.display(), e);
                            return Err(format!("lower_and_compile: cannot create output file at {}: {}", dp.display(), e));
                        }
                    }
                    println!("[host lower_and_compile] precreate exists={}", dp.exists());
                }
                // Write rust src to temp and run rustc -o dest
                // Use file_ops helpers for temp file and output handling
                let src_path = create_temp_file("generated_main.rs").map_err(|e| {
                    log_to_file("boot_host.log", &format!("[lower_and_compile] temp file error: {}", e));
                    format!("lower_and_compile: failed to create temp file: {}", e)
                })?;
                write_to_file(&src_path, &rust_src).map_err(|e| {
                    log_to_file("boot_host.log", &format!("[lower_and_compile] write error: {}", e));
                    format!("lower_and_compile: failed to write rust src: {}", e)
                })?;
                let rustc = std::env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());
                let tmp_out = create_temp_file("patlang_native_out").map_err(|e| {
                    log_to_file("boot_host.log", &format!("[lower_and_compile] temp out error: {}", e));
                    format!("lower_and_compile: failed to create temp out: {}", e)
                })?;
                let status = std::process::Command::new(&rustc)
                    .arg("-O")
                    .arg(&src_path)
                    .arg("-o")
                    .arg(&tmp_out)
                    .status()
                    .map_err(|e| {
                        log_to_file("boot_host.log", &format!("[lower_and_compile] rustc error: {}", e));
                        format!("lower_and_compile: failed to run rustc: {}", e)
                    })?;
                if !status.success() {
                    log_to_file("boot_host.log", &format!("[lower_and_compile] rustc failed: status={}", status));
                    return Err(format!("lower_and_compile: rustc failed with status {}", status));
                }
                // Move/copy to final output
                move_or_copy(&tmp_out, &dest_path).map_err(|e| {
                    log_to_file("boot_host.log", &format!("[lower_and_compile] move/copy error: {}", e));
                    format!("lower_and_compile: failed to move/copy output: {}", e)
                })?;
                if file_exists(&dest_path) {
                    Ok(Value::String(dest_path))
                } else {
                    log_to_file("boot_host.log", &format!("[lower_and_compile] output not found: {}", dest_path));
                    Err(format!("lower_and_compile: expected output '{}' not found after rustc", dest_path))
                }
            }
            ,
            "emit_rust_for" => {
                // Accepts: emit_rust_for(programObj)
                if args.is_empty() { return Err("emit_rust_for: expected program object".into()); }
                let src_path = match &args[0] {
                    Value::Object(map) => match map.get("source_path") { Some(Value::String(s)) => s.clone(), _ => String::new() },
                    Value::String(s) => s.clone(),
                    other => display_value(other),
                };
                // Find pat
                let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
                let rel_candidates = [
                    "rust-runtime/target/debug/pat",
                    "rust-runtime/target/debug/pat.exe",
                    "./rust-runtime/target/debug/pat",
                    "./rust-runtime/target/debug/pat.exe",
                    "..\\rust-runtime\\target\\debug\\pat.exe",
                    "rust-runtime\\target\\debug\\pat.exe",
                ];
                let abs_candidates: Vec<String> = rel_candidates.iter().map(|p| cwd.join(p).display().to_string()).collect();
                let pat_path = abs_candidates.iter().find(|p| std::path::Path::new(p).exists()).cloned()
                    .ok_or_else(|| format!("emit_rust_for: could not find pat runner. Checked:\n{}", abs_candidates.join("\n")))?;
                // Normalize input
                fn msys_to_win_path(p: &str) -> String {
                    #[cfg(windows)]
                    {
                        let b = p.as_bytes();
                        if b.len() >= 3 && b[0] == b'/' && b[2] == b'/' {
                            let drive = (b[1] as char).to_ascii_uppercase();
                            let rest = &p[3..];
                            let rest_bs = rest.replace('/', "\\");
                            return format!("{}:\\{}", drive, rest_bs);
                        }
                        return p.replace('/', "\\");
                    }
                    #[cfg(not(windows))]
                    { p.to_string() }
                }
                let input_abs = {
                    let p = std::path::Path::new(&src_path);
                    if p.is_absolute() { p.to_path_buf() } else { std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from(".")).join(p) }
                };
                let input_arg = msys_to_win_path(&input_abs.display().to_string());
                // Run emit-rust
                let mut cmd = std::process::Command::new(&pat_path);
                if let Ok(cwd) = std::env::current_dir() { let _ = cmd.current_dir(&cwd); }
                cmd.arg("--emit-rust");
                if !input_arg.is_empty() { cmd.arg(&input_arg); }
                let out = cmd.output().map_err(|e| format!("emit_rust_for: failed to spawn pat: {}", e))?;
                if !out.status.success() {
                    return Err(format!("emit_rust_for: pat exited with {}\n{}", out.status, String::from_utf8_lossy(&out.stderr)));
                }
                let combined = format!("{}\n{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
                let mut rs_path: Option<String> = None;
                for line in combined.lines() {
                    let l = line.trim();
                    if let Some(rest) = l.strip_prefix("Wrote ") {
                        let p = rest.trim();
                        if p.ends_with(".rs") { rs_path = Some(p.to_string()); }
                    }
                }
                if rs_path.is_none() {
                    if let Ok(mut entries) = std::fs::read_dir(&cwd) {
                        let mut newest: Option<(std::time::SystemTime, String)> = None;
                        while let Some(Ok(e)) = entries.next() {
                            if let Some(name) = e.file_name().to_str() {
                                if name.ends_with(".rs") && name.starts_with("emitted_") {
                                    if let Ok(md) = e.metadata() {
                                        if let Ok(t) = md.modified() {
                                            let path_str = e.path().display().to_string();
                                            newest = match newest {
                                                Some((prev_t, _)) => if t > prev_t { Some((t, path_str)) } else { newest },
                                                None => Some((t, path_str)),
                                            };
                                        }
                                    }
                                }
                            }
                        }
                        if let Some((_, p)) = newest { rs_path = Some(p); }
                    }
                }
                match rs_path { Some(p) => Ok(Value::String(p)), None => Err("emit_rust_for: could not find emitted .rs".into()) }
            }
            ,
            "copy_file" => {
                // copy_file(from, to) -> "OK <abs>" or "ERR: msg"
                if args.len() != 2 { return Err("copy_file: expected 2 args".into()); }
                let from = to_s(&args[0]);
                let to = to_s(&args[1]);
                let from_p = std::path::Path::new(&from);
                let to_p = std::path::Path::new(&to);
                if let Some(par) = to_p.parent() { let _ = std::fs::create_dir_all(par); }
                match std::fs::copy(from_p, to_p) {
                    Ok(_) => {
                        let abs = std::fs::canonicalize(to_p).unwrap_or_else(|_| to_p.to_path_buf());
                        Ok(Value::String(format!("OK {}", abs.display())))
                    }
                    Err(e) => Ok(Value::String(format!("ERR: {}", e)))
                }
            }
            ,
            "patc_compile_from_argv" => {
                // Parse argv: [exe, [--patc|--emit-rust], input, [--out, path]]
                println!("[patc_compile] ENTER");
                let mut argsv: Vec<String> = std::env::args().collect();
                if !argsv.is_empty() { argsv.remove(0); }
                let mut mode = "patc".to_string();
                let mut input = String::new();
                let mut out_path: Option<String> = None;
                let mut i = 0usize;
                while i < argsv.len() {
                    let a = &argsv[i];
                    if a == "--emit-rust" { mode = "emit-rust".to_string(); i += 1; continue; }
                    if a == "--patc" { mode = "patc".to_string(); i += 1; continue; }
                    if a == "--out" { if i+1 < argsv.len() { out_path = Some(argsv[i+1].clone()); i += 2; continue; } else { break; } }
                    if input.is_empty() { input = a.clone(); i += 1; continue; }
                    i += 1;
                }
                println!("[patc_compile] mode={} input='{}' out={}", mode, input, out_path.clone().unwrap_or_default());
                if input.is_empty() { println!("[patc_compile] no input provided"); return Ok(Value::String("ERR: usage --patc <input.patlang> [--out path]".into())); }
                // Reuse logic from lower_and_compile
                let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
                let mut abs_candidates: Vec<String> = Vec::new();
                let mut push_candidate = |base: &std::path::Path, rel: &str| {
                    abs_candidates.push(base.join(rel).display().to_string());
                };
                // Candidates relative to CWD
                push_candidate(&cwd, "target/debug/pat");
                push_candidate(&cwd, "target/debug/pat.exe");
                push_candidate(&cwd, "rust-runtime/target/debug/pat");
                push_candidate(&cwd, "rust-runtime/target/debug/pat.exe");
                push_candidate(&cwd, "./rust-runtime/target/debug/pat");
                push_candidate(&cwd, "./rust-runtime/target/debug/pat.exe");
                // Candidates relative to parent of CWD
                if let Some(parent) = cwd.parent() {
                    push_candidate(parent, "rust-runtime/target/debug/pat");
                    push_candidate(parent, "rust-runtime/target/debug/pat.exe");
                }
                let pat_path = abs_candidates.iter().find(|p| std::path::Path::new(p).exists()).cloned()
                    .unwrap_or_else(|| "pat".to_string());
                println!("[patc_compile] pat candidates:\n{}\n[patc_compile] using pat at {}", abs_candidates.join("\n"), pat_path);

                fn msys_to_win_path(p: &str) -> String {
                    #[cfg(windows)]
                    {
                        let b = p.as_bytes();
                        if b.len() >= 3 && b[0] == b'/' && b[2] == b'/' {
                            let drive = (b[1] as char).to_ascii_uppercase();
                            let rest = &p[3..];
                            let rest_bs = rest.replace('/', "\\");
                            return format!("{}:\\{}", drive, rest_bs);
                        }
                        return p.replace('/', "\\");
                    }
                    #[cfg(not(windows))]
                    { p.to_string() }
                }
                let input_abs = {
                    let p = std::path::Path::new(&input);
                    if p.is_absolute() { p.to_path_buf() } else { std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from(".")).join(p) }
                };
                let input_arg = msys_to_win_path(&input_abs.display().to_string());
                println!("[patc_compile] input_abs={} input_arg={}", input_abs.display(), input_arg);
                // Emit rust path
                let mut cmd = std::process::Command::new(&pat_path);
                if let Ok(cwd) = std::env::current_dir() { let _ = cmd.current_dir(&cwd); }
                cmd.arg("--emit-rust");
                if !input_arg.is_empty() { cmd.arg(&input_arg); }
                let outp = cmd.output().map_err(|e| format!("patc_compile_from_argv: failed to run pat: {}", e))?;
                if !outp.status.success() { println!("[patc_compile] stage0 pat failed: {}", outp.status); return Ok(Value::String(format!("ERR: {}", String::from_utf8_lossy(&outp.stderr)))); }
                let out_stdout_s = String::from_utf8_lossy(&outp.stdout).to_string();
                let out_stderr_s = String::from_utf8_lossy(&outp.stderr).to_string();
                let combined = format!("{}\n{}", out_stdout_s, out_stderr_s);
                let mut rs_path: Option<String> = None;
                for line in combined.lines() {
                    let l = line.trim();
                    if let Some(rest) = l.strip_prefix("Wrote ") { let p = rest.trim(); if p.ends_with(".rs") { rs_path = Some(p.to_string()); } }
                }
                let mut rust_src_inline: Option<String> = None;
                if rs_path.is_none() && !out_stdout_s.trim().is_empty() {
                    rust_src_inline = Some(out_stdout_s.clone());
                }
                println!("[patc_compile] rs_path={:?} inline_len={}", rs_path, rust_src_inline.as_ref().map(|s| s.len()).unwrap_or(0));
                if mode == "emit-rust" {
                    if let Some(p) = rs_path { return Ok(Value::String(p)); }
                    if let Some(src) = rust_src_inline {
                        let mut t = std::env::temp_dir(); t.push("patlang_emit_inline"); let _ = std::fs::create_dir_all(&t);
                        let f = t.join("inline.rs");
                        if let Err(e) = std::fs::write(&f, &src) { return Ok(Value::String(format!("ERR: write inline: {}", e))); }
                        return Ok(Value::String(f.display().to_string()));
                    }
                    return Ok(Value::String("ERR: no emitted rust found".into()));
                }
                // Compile to exe
                let dest_path: String = if let Some(d) = out_path { d } else {
                    let stem = std::path::Path::new(&input_arg).file_stem().and_then(|s| s.to_str()).unwrap_or("a");
                    let parent = std::path::Path::new(&input_arg).parent().unwrap_or_else(|| std::path::Path::new("."));
                    let mut outp = parent.join(stem);
                    if cfg!(windows) { outp.set_extension("exe"); }
                    outp.display().to_string()
                };
                // Reserved device name protection on Windows
                #[cfg(windows)]
                {
                    use std::path::Path;
                    let base = Path::new(&dest_path).file_stem().and_then(|s| s.to_str()).unwrap_or("").to_ascii_uppercase();
                    let reserved = [
                        "CON","PRN","AUX","NUL",
                        "COM1","COM2","COM3","COM4","COM5","COM6","COM7","COM8","COM9",
                        "LPT1","LPT2","LPT3","LPT4","LPT5","LPT6","LPT7","LPT8","LPT9"
                    ];
                    if reserved.contains(&base.as_str()) {
                        return Ok(Value::String(format!("ERR: '{}' is a reserved Windows filename; choose a different output name", base)));
                    }
                }
                let rust_src = if let Some(src) = rust_src_inline { src } else {
                    let p = rs_path.unwrap_or_else(|| cwd.join("emitted_bootstrap.rs").display().to_string());
                    std::fs::read_to_string(&p).map_err(|e| format!("patc_compile_from_argv: read {}: {}", p, e))?
                };
                let src_path = create_temp_file("generated_main.rs").map_err(|e| {
                    log_to_file("boot_host.log", &format!("[patc_compile_from_argv] temp file error: {}", e));
                    format!("patc_compile_from_argv: failed to create temp file: {}", e)
                })?;
                write_to_file(&src_path, &rust_src).map_err(|e| {
                    log_to_file("boot_host.log", &format!("[patc_compile_from_argv] write error: {}", e));
                    format!("patc_compile_from_argv: failed to write rust src: {}", e)
                })?;
                let rustc = std::env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());
                let tmp_out = create_temp_file("patlang_native_out").map_err(|e| {
                    log_to_file("boot_host.log", &format!("[patc_compile_from_argv] temp out error: {}", e));
                    format!("patc_compile_from_argv: failed to create temp out: {}", e)
                })?;
                let status = std::process::Command::new(&rustc)
                    .arg("-O").arg(&src_path).arg("-o").arg(&tmp_out)
                    .status().map_err(|e| {
                        log_to_file("boot_host.log", &format!("[patc_compile_from_argv] rustc error: {}", e));
                        format!("patc_compile_from_argv: rustc: {}", e)
                    })?;
                if !status.success() {
                    log_to_file("boot_host.log", &format!("[patc_compile_from_argv] rustc failed: status={}", status));
                    return Ok(Value::String(format!("ERR: rustc failed ({})", status)));
                }
                move_or_copy(&tmp_out, &dest_path).map_err(|e| {
                    log_to_file("boot_host.log", &format!("[patc_compile_from_argv] move/copy error: {}", e));
                    format!("patc_compile_from_argv: failed to move/copy output: {}", e)
                })?;
                if file_exists(&dest_path) {
                    Ok(Value::String(dest_path))
                } else {
                    log_to_file("boot_host.log", &format!("[patc_compile_from_argv] output not found: {}", dest_path));
                    Ok(Value::String(format!("ERR: expected output '{}' not found after rustc", dest_path)))
                }
            }
            "get_argv" => {
                // Mimic `pat ./patc_native.patlang <input> [--out path]` argv shape expected by patc_native:
                // Prepend a synthetic script name so indexing matches (argv[0] is the script path).
                // Also drop the original script path (args[1]) from the rest so argv[1] is the first real argument.
                let mut rest: Vec<String> = std::env::args().collect();
                if !rest.is_empty() { rest.remove(0); } // drop exe
                let script_path = if !rest.is_empty() { Some(rest.remove(0)) } else { None }; // drop script
                let mut full = Vec::with_capacity(rest.len()+1);
                let fake0 = script_path
                    .as_ref()
                    .and_then(|s| std::path::Path::new(s).file_name().map(|f| f.to_string_lossy().to_string()))
                    .unwrap_or_else(|| "patc_native.patlang".to_string());
                full.push(format!("./{}", fake0));
                full.extend(rest);
                Ok(Value::List(full.into_iter().map(Value::String).collect()))
            }
            "list_get" => {
                // list_get(list, index)
                if args.len() != 2 { return Err("expected 2 args".into()); }
                let idx = match &args[1] { Value::Number(n) => *n as usize, Value::String(s) => s.parse::<usize>().unwrap_or(0), _ => 0 };
                match &args[0] {
                    Value::List(xs) => Ok(xs.get(idx).cloned().unwrap_or(Value::Unit)),
                    Value::String(s) => {
                        if s.is_ascii() {
                            return Ok(match s.as_bytes().get(idx) { Some(b) => Value::String((*b as char).to_string()), None => Value::String(String::new()) });
                        }
                        let ch = s.chars().nth(idx).unwrap_or('\0');
                        Ok(Value::String(if ch == '\0' { String::new() } else { ch.to_string() }))
                    }
                    _ => Ok(Value::Unit),
                }
            }
            "list_len" => {
                // list_len(listOrString) -> String count (to match Stage 0 builtins)
                if args.len() != 1 { return Err("expected 1 arg".into()); }
                let n = match &args[0] {
                    Value::List(xs) => xs.len(),
                    Value::String(s) => s.chars().count(),
                    _ => 0,
                };
                Ok(Value::String(n.to_string()))
            }
            "list_push" => {
                // list_push(list, item) -> new list with item appended
                if args.len() != 2 { return Err("list_push: expected 2 args".into()); }
                let mut xs = match &args[0] {
                    Value::List(xs) => xs.clone(),
                    Value::Unit => Vec::new(),
                    _ => return Err("list_push: expected list".into()),
                };
                xs.push(args[1].clone());
                Ok(Value::List(xs))
            }
            "list_set" => {
                // list_set(list, index, value) -> new list with element replaced
                if args.len() != 3 { return Err("list_set: expected 3 args".into()); }
                let mut xs = match &args[0] {
                    Value::List(xs) => xs.clone(),
                    _ => return Err("list_set: expected list".into()),
                };
                let idx = match &args[1] { Value::Number(n) => *n as usize, Value::String(s) => s.parse::<usize>().unwrap_or(usize::MAX), _ => usize::MAX };
                if idx >= xs.len() { return Err(format!("list_set: index {} out of range (len {})", idx, xs.len())); }
                xs[idx] = args[2].clone();
                Ok(Value::List(xs))
            }
            "vec_new" => {
                let id = VECS.with(|v| { let mut b = v.borrow_mut(); b.push(Vec::new()); b.len() - 1 });
                Ok(Value::Number(id as f64))
            }
            "vec_push" => {
                let id = arg_usize(&args, 0, "vec_push")?;
                let item = args.get(1).cloned().unwrap_or(Value::Unit);
                VECS.with(|v| {
                    let mut b = v.borrow_mut();
                    b.get_mut(id).ok_or_else(|| format!("vec_push: unknown vec {}", id)).map(|xs| xs.push(item))
                })?;
                Ok(Value::Unit)
            }
            "vec_set" => {
                let id = arg_usize(&args, 0, "vec_set")?;
                let idx = arg_usize(&args, 1, "vec_set")?;
                let item = args.get(2).cloned().unwrap_or(Value::Unit);
                VECS.with(|v| {
                    let mut b = v.borrow_mut();
                    let xs = b.get_mut(id).ok_or_else(|| format!("vec_set: unknown vec {}", id))?;
                    if idx >= xs.len() { return Err(format!("vec_set: index {} out of range (len {})", idx, xs.len())); }
                    xs[idx] = item;
                    Ok(())
                })?;
                Ok(Value::Unit)
            }
            "vec_get" => {
                let id = arg_usize(&args, 0, "vec_get")?;
                let idx = arg_usize(&args, 1, "vec_get")?;
                VECS.with(|v| {
                    let b = v.borrow();
                    b.get(id).ok_or_else(|| format!("vec_get: unknown vec {}", id))
                        .map(|xs| xs.get(idx).cloned().unwrap_or(Value::Unit))
                })
            }
            "vec_len" => {
                let id = arg_usize(&args, 0, "vec_len")?;
                VECS.with(|v| {
                    let b = v.borrow();
                    b.get(id).ok_or_else(|| format!("vec_len: unknown vec {}", id)).map(|xs| Value::Number(xs.len() as f64))
                })
            }
            "vec_to_list" => {
                let id = arg_usize(&args, 0, "vec_to_list")?;
                VECS.with(|v| {
                    let b = v.borrow();
                    b.get(id).ok_or_else(|| format!("vec_to_list: unknown vec {}", id)).map(|xs| Value::List(xs.clone()))
                })
            }
            "str_intern" => {
                let s = match args.get(0) { Some(Value::String(s)) => s.clone(), Some(v) => to_s(v), None => String::new() };
                let id = ISTRINGS.with(|v| { let mut b = v.borrow_mut(); b.push(s); b.len() - 1 });
                Ok(Value::Number(id as f64))
            }
            "sc_len" => {
                let id = arg_usize(&args, 0, "sc_len")?;
                ISTRINGS.with(|v| {
                    let b = v.borrow();
                    b.get(id).ok_or_else(|| format!("sc_len: unknown string {}", id))
                        .map(|s| Value::Number(if s.is_ascii() { s.len() as f64 } else { s.chars().count() as f64 }))
                })
            }
            "sc_code" => {
                let id = arg_usize(&args, 0, "sc_code")?;
                let idx = arg_usize(&args, 1, "sc_code")?;
                ISTRINGS.with(|v| {
                    let b = v.borrow();
                    let s = b.get(id).ok_or_else(|| format!("sc_code: unknown string {}", id))?;
                    if s.is_ascii() {
                        return Ok(Value::Number(match s.as_bytes().get(idx) { Some(c) => *c as f64, None => -1.0 }));
                    }
                    Ok(Value::Number(match s.chars().nth(idx) { Some(c) => c as u32 as f64, None => -1.0 }))
                })
            }
            "sc_char" => {
                let id = arg_usize(&args, 0, "sc_char")?;
                let idx = arg_usize(&args, 1, "sc_char")?;
                ISTRINGS.with(|v| {
                    let b = v.borrow();
                    let s = b.get(id).ok_or_else(|| format!("sc_char: unknown string {}", id))?;
                    if s.is_ascii() {
                        return Ok(match s.as_bytes().get(idx) { Some(c) => Value::String((*c as char).to_string()), None => Value::String(String::new()) });
                    }
                    Ok(match s.chars().nth(idx) { Some(c) => Value::String(c.to_string()), None => Value::String(String::new()) })
                })
            }
            "sb_new" => {
                let id = SBUFS.with(|v| { let mut b = v.borrow_mut(); b.push(String::new()); b.len() - 1 });
                Ok(Value::Number(id as f64))
            }
            "sb_push" => {
                let id = arg_usize(&args, 0, "sb_push")?;
                let text = match args.get(1) { Some(Value::String(s)) => s.clone(), Some(v) => to_s(v), None => String::new() };
                SBUFS.with(|v| {
                    let mut b = v.borrow_mut();
                    b.get_mut(id).ok_or_else(|| format!("sb_push: unknown buffer {}", id)).map(|s| s.push_str(&text))
                })?;
                Ok(Value::Unit)
            }
            "sb_str" => {
                let id = arg_usize(&args, 0, "sb_str")?;
                SBUFS.with(|v| {
                    let b = v.borrow();
                    b.get(id).ok_or_else(|| format!("sb_str: unknown buffer {}", id)).map(|s| Value::String(s.clone()))
                })
            }
            "char_code" => {
                // char_code(string, index) -> Number code point, or -1 if out of range
                if args.len() != 2 { return Err("char_code: expected 2 args".into()); }
                let s = match &args[0] { Value::String(s) => s.clone(), v => to_s(v) };
                let idx = match &args[1] { Value::Number(n) => *n as usize, Value::String(t) => t.parse::<usize>().unwrap_or(usize::MAX), _ => usize::MAX };
                if s.is_ascii() {
                    return Ok(Value::Number(match s.as_bytes().get(idx) { Some(b) => *b as f64, None => -1.0 }));
                }
                match s.chars().nth(idx) {
                    Some(c) => Ok(Value::Number(c as u32 as f64)),
                    None => Ok(Value::Number(-1.0)),
                }
            }
            "substr" => {
                // substr(string, start, len) -> String slice by chars (clamped)
                if args.len() != 3 { return Err("substr: expected 3 args".into()); }
                let s = match &args[0] { Value::String(s) => s.clone(), v => to_s(v) };
                let start = match &args[1] { Value::Number(n) => (*n).max(0.0) as usize, Value::String(t) => t.parse::<usize>().unwrap_or(0), _ => 0 };
                let count = match &args[2] { Value::Number(n) => (*n).max(0.0) as usize, Value::String(t) => t.parse::<usize>().unwrap_or(0), _ => 0 };
                if s.is_ascii() {
                    let b = s.as_bytes();
                    let st = start.min(b.len());
                    let en = st.saturating_add(count).min(b.len());
                    return Ok(Value::String(String::from_utf8_lossy(&b[st..en]).to_string()));
                }
                Ok(Value::String(s.chars().skip(start).take(count).collect()))
            }
            "chr" => {
                // chr(code) -> 1-char string (empty for invalid code points)
                let n = match args.get(0) { Some(Value::Number(n)) => *n, Some(Value::String(s)) => s.trim().parse::<f64>().unwrap_or(-1.0), _ => -1.0 };
                if n < 0.0 { return Ok(Value::String(String::new())); }
                Ok(Value::String(char::from_u32(n as u32).map(|c| c.to_string()).unwrap_or_default()))
            }
            "to_num" => {
                // to_num(value) -> Number (parse string, else 0)
                let v = args.get(0).cloned().unwrap_or(Value::Unit);
                let n = match v {
                    Value::Number(n) => n,
                    Value::String(s) => s.trim().parse::<f64>().unwrap_or(0.0),
                    Value::Bool(b) => if b { 1.0 } else { 0.0 },
                    _ => 0.0,
                };
                Ok(Value::Number(n))
            }
            "read_file" => {
                // read_file(path) -> String contents
                let p = match args.get(0) { Some(Value::String(s)) => s.clone(), Some(v) => to_s(v), None => String::new() };
                std::fs::read_to_string(&p).map(Value::String).map_err(|e| format!("read_file: {}: {}", p, e))
            }
            "now_ms" => {
                // now_ms() -> Number: milliseconds since the Unix epoch
                let ms = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .map(|d| d.as_millis() as f64)
                    .unwrap_or(0.0);
                Ok(Value::Number(ms))
            }
            "write_file" => {
                // write_file(path, contents) -> Bool
                let p = match args.get(0) { Some(Value::String(s)) => s.clone(), Some(v) => to_s(v), None => String::new() };
                let contents = match args.get(1) { Some(Value::String(s)) => s.clone(), Some(v) => to_s(v), None => String::new() };
                if let Some(parent) = std::path::Path::new(&p).parent() { let _ = std::fs::create_dir_all(parent); }
                std::fs::write(&p, contents).map(|_| Value::Bool(true)).map_err(|e| format!("write_file: {}: {}", p, e))
            }
            "argv" => {
                // argv() -> List of user arguments (program name stripped)
                let mut rest: Vec<String> = std::env::args().collect();
                if !rest.is_empty() { rest.remove(0); }
                Ok(Value::List(rest.into_iter().map(Value::String).collect()))
            }
            "rustc_build" => {
                // rustc_build(rust_source, out_path[, target_triple]) -> artifact path.
                // The self-hosted compiler's back end: write source, run rustc.
                // Optional target triple (e.g. "wasm32-wasip1") cross-compiles.
                let src = match args.get(0) { Some(Value::String(s)) => s.clone(), _ => return Err("rustc_build: expected Rust source string".into()) };
                let out = match args.get(1) { Some(Value::String(s)) if !s.trim().is_empty() => s.clone(), _ => return Err("rustc_build: expected output path".into()) };
                let target = match args.get(2) { Some(Value::String(s)) if !s.trim().is_empty() => Some(s.clone()), _ => None };
                let mut tmp = std::env::temp_dir();
                tmp.push("patlang_selfhost_build");
                std::fs::create_dir_all(&tmp).map_err(|e| format!("rustc_build: temp dir: {}", e))?;
                let src_path = tmp.join(format!("gen_{}.rs", std::process::id()));
                std::fs::write(&src_path, &src).map_err(|e| format!("rustc_build: write {}: {}", src_path.display(), e))?;
                if let Some(parent) = std::path::Path::new(&out).parent() { let _ = std::fs::create_dir_all(parent); }
                let rustc = std::env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());
                let mut cmd = std::process::Command::new(&rustc);
                cmd.arg("-O").arg(&src_path).arg("-o").arg(&out);
                if let Some(t) = &target { cmd.arg("--target").arg(t); }
                let status = cmd.status().map_err(|e| format!("rustc_build: failed to run rustc: {}", e))?;
                if !status.success() { return Err(format!("rustc_build: rustc failed with status {}", status)); }
                let p = std::path::Path::new(&out);
                let abs = std::fs::canonicalize(p).unwrap_or_else(|_| p.to_path_buf());
                Ok(Value::String(abs.display().to_string()))
            }
            "contract_check" => {
                // contract_check(func_name, kind, text, ok) - design-by-contract
                // enforcement, identical semantics to the interpreter's host arm.
                if args.len() != 4 { return Err("contract_check: expected 4 args".into()); }
                let func = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let kind = match &args[1] { Value::String(s) => s.clone(), _ => String::new() };
                let text = match &args[2] { Value::String(s) => s.clone(), _ => String::new() };
                let ok = args[3].as_bool()?;
                if ok {
                    Ok(Value::Unit)
                } else {
                    let label = match kind.as_str() {
                        "require" => "precondition",
                        "ensure" => "postcondition",
                        _ => "assertion",
                    };
                    Err(format!("contract violation: {} failed in {}(): {}", label, func, text))
                }
            }
            "run_ir" => {
                // run_ir(ir_shape): decode a freshly lowered IR shape and run
                // it on this runtime's VM (the browser-playground back end)
                fn sl(v: &Value) -> Result<&Vec<Value>, String> {
                    match v { Value::List(xs) => Ok(xs), _ => Err("run_ir: expected list node".into()) }
                }
                fn st(xs: &[Value], i: usize) -> Result<String, String> {
                    match xs.get(i) { Some(Value::String(s)) => Ok(s.clone()), _ => Err("run_ir: expected string".into()) }
                }
                fn snum(xs: &[Value], i: usize) -> Result<f64, String> {
                    match xs.get(i) {
                        Some(Value::Number(n)) => Ok(*n),
                        Some(Value::String(s)) => s.trim().parse::<f64>().map_err(|_| "run_ir: expected number".to_string()),
                        _ => Err("run_ir: expected number".into()),
                    }
                }
                fn dinstr(v: &Value) -> Result<Instr, String> {
                    let xs = sl(v)?;
                    let tag = st(xs, 0)?;
                    Ok(match tag.as_str() {
                        "Const" => {
                            let kind = st(xs, 1)?; let text = st(xs, 2)?;
                            let val = match kind.as_str() {
                                "num" => Value::Number(text.trim().parse::<f64>().map_err(|_| "run_ir: bad number".to_string())?),
                                "str" => Value::String(text),
                                _ => Value::Bool(text == "true"),
                            };
                            Instr::Const(val)
                        }
                        "Load" => Instr::LoadLocal(st(xs, 1)?),
                        "Store" => Instr::StoreLocal(st(xs, 1)?),
                        "Bin" => {
                            let op = st(xs, 1)?;
                            let k = match op.as_str() {
                                "+" => BinOpKind::Add, "-" => BinOpKind::Sub, "*" => BinOpKind::Mul,
                                "/" => BinOpKind::Div, "%" => BinOpKind::Mod,
                                "==" => BinOpKind::Eq, "!=" => BinOpKind::Ne,
                                "<" => BinOpKind::Lt, "<=" => BinOpKind::Le,
                                ">" => BinOpKind::Gt, ">=" => BinOpKind::Ge,
                                "and" => BinOpKind::And, _ => BinOpKind::Or,
                            };
                            Instr::BinOp(k)
                        }
                        "Un" => { if st(xs, 1)? == "not" { Instr::UnOp(UnOpKind::Not) } else { Instr::UnOp(UnOpKind::Neg) } }
                        "Jump" => Instr::Jump(snum(xs, 1)? as usize),
                        "JumpIfFalse" => Instr::JumpIfFalse(snum(xs, 1)? as usize),
                        "CallHost" => Instr::CallHost(st(xs, 1)?, snum(xs, 2)? as usize),
                        "Call" => Instr::Call(st(xs, 1)?, snum(xs, 2)? as usize),
                        "MakeClosure" => {
                            let func_name = st(xs, 1)?;
                            let names_list = sl(xs.get(2).ok_or("run_ir: MakeClosure missing captured names")?)?;
                            let mut captured_names = Vec::with_capacity(names_list.len());
                            for nv in names_list {
                                captured_names.push(match nv { Value::String(s) => s.clone(), _ => return Err("run_ir: captured name must be a string".into()) });
                            }
                            Instr::MakeClosure(func_name, captured_names)
                        }
                        "CallValue" => Instr::CallValue(snum(xs, 1)? as usize),
                        "BuildList" => Instr::BuildList(snum(xs, 1)? as usize),
                        _ => Instr::Return,
                    })
                }
                let shape = args.get(0).ok_or("run_ir: expected IR shape")?;
                let xs = sl(shape)?;
                if st(xs, 0)? != "ProgramIR" { return Err("run_ir: root must be ProgramIR".into()); }
                let entry = st(xs, 1)?;
                let mut program = Program { functions: HashMap::new(), entry: entry.clone() };
                for fv in sl(xs.get(2).ok_or("run_ir: missing functions")?)? {
                    let fx = sl(fv)?;
                    let name = st(fx, 1)?;
                    let params: Vec<String> = sl(fx.get(2).ok_or("run_ir: missing params")?)?
                        .iter().map(|p| match p { Value::String(s) => Ok(s.clone()), _ => Err("run_ir: bad param".to_string()) })
                        .collect::<Result<_, _>>()?;
                    let mut body = Vec::new();
                    for iv in sl(fx.get(3).ok_or("run_ir: missing body")?)? { body.push(dinstr(iv)?); }
                    program.functions.insert(name.clone(), Function { name, params, body });
                }
                for ev in sl(xs.get(3).ok_or("run_ir: missing events")?)? {
                    let ex = sl(ev)?;
                    let event = st(ex, 1)?; let handler = st(ex, 2)?;
                    EVENT_HANDLERS.with(|m| m.borrow_mut().entry(event).or_insert_with(Vec::new).push(handler));
                }
                let f = program.functions.get(&program.entry).ok_or("run_ir: entry not found")?;
                run_function(&program, f, &[])
            }
            "tcp_listen" => {
                // tcp_listen(port) -> Number actual bound port (0 = OS-assigned)
                let port = arg_num(&args, 0, "tcp_listen")? as u16;
                let listener = std::net::TcpListener::bind(("127.0.0.1", port))
                    .map_err(|e| format!("tcp_listen: bind {}: {}", port, e))?;
                let actual = listener.local_addr().map_err(|e| format!("tcp_listen: {}", e))?.port();
                LISTENERS.with(|l| l.borrow_mut().insert(actual, listener));
                Ok(Value::Number(actual as f64))
            }
            "tcp_accept" => {
                // tcp_accept(port) -> Number connection id (blocks)
                let port = arg_num(&args, 0, "tcp_accept")? as u16;
                let listener = LISTENERS.with(|l| l.borrow().get(&port).map(|x| x.try_clone()))
                    .ok_or_else(|| format!("tcp_accept: no listener on port {}", port))?
                    .map_err(|e| format!("tcp_accept: {}", e))?;
                let (stream, _) = listener.accept().map_err(|e| format!("tcp_accept: {}", e))?;
                let id = NEXT_CONN.with(|n| { let mut b = n.borrow_mut(); let v = *b; *b += 1; v });
                CONNS.with(|c| c.borrow_mut().insert(id, stream));
                Ok(Value::Number(id as f64))
            }
            "sleep_ms" => {
                let ms = arg_num(&args, 0, "sleep_ms")?.max(0.0) as u64;
                std::thread::sleep(std::time::Duration::from_millis(ms));
                Ok(Value::Unit)
            }
            "tcp_accept_timeout" => {
                // tcp_accept_timeout(port, ms) -> conn id, or -1 on timeout
                let port = arg_num(&args, 0, "tcp_accept_timeout")? as u16;
                let ms = arg_num(&args, 1, "tcp_accept_timeout")?.max(0.0) as u64;
                let listener = LISTENERS.with(|l| l.borrow().get(&port).map(|x| x.try_clone()))
                    .ok_or_else(|| format!("tcp_accept_timeout: no listener on port {}", port))?
                    .map_err(|e| format!("tcp_accept_timeout: {}", e))?;
                listener.set_nonblocking(true).map_err(|e| format!("tcp_accept_timeout: {}", e))?;
                let deadline = std::time::Instant::now() + std::time::Duration::from_millis(ms);
                loop {
                    match listener.accept() {
                        Ok((stream, _)) => {
                            let _ = stream.set_nonblocking(false);
                            let id = NEXT_CONN.with(|n| { let mut b = n.borrow_mut(); let v = *b; *b += 1; v });
                            CONNS.with(|c| c.borrow_mut().insert(id, stream));
                            return Ok(Value::Number(id as f64));
                        }
                        Err(ref e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                            if std::time::Instant::now() >= deadline { return Ok(Value::Number(-1.0)); }
                            std::thread::sleep(std::time::Duration::from_millis(2));
                        }
                        Err(e) => return Err(format!("tcp_accept_timeout: {}", e)),
                    }
                }
            }
            "tcp_read" => {
                // tcp_read(conn) -> String (single read, up to 64 KiB)
                use std::io::Read;
                let id = arg_num(&args, 0, "tcp_read")? as usize;
                let mut stream = CONNS.with(|c| c.borrow().get(&id).map(|s| s.try_clone()))
                    .ok_or_else(|| format!("tcp_read: unknown connection {}", id))?
                    .map_err(|e| format!("tcp_read: {}", e))?;
                let mut buf = vec![0u8; 65536];
                let n = stream.read(&mut buf).map_err(|e| format!("tcp_read: {}", e))?;
                Ok(Value::String(String::from_utf8_lossy(&buf[..n]).to_string()))
            }
            "tcp_write" => {
                // tcp_write(conn, data) -> Bool
                use std::io::Write;
                let id = arg_num(&args, 0, "tcp_write")? as usize;
                let data = match args.get(1) { Some(Value::String(s)) => s.clone(), Some(v) => to_s(v), None => String::new() };
                let mut stream = CONNS.with(|c| c.borrow().get(&id).map(|s| s.try_clone()))
                    .ok_or_else(|| format!("tcp_write: unknown connection {}", id))?
                    .map_err(|e| format!("tcp_write: {}", e))?;
                stream.write_all(data.as_bytes()).map_err(|e| format!("tcp_write: {}", e))?;
                let _ = stream.flush();
                Ok(Value::Bool(true))
            }
            "tcp_close" => {
                use std::io::Read;
                let id = arg_num(&args, 0, "tcp_close")? as usize;
                if let Some(stream) = CONNS.with(|c| c.borrow_mut().remove(&id)) {
                    // Drain unread inbound bytes and half-close so the peer
                    // gets a graceful FIN rather than an RST
                    let _ = stream.set_nonblocking(true);
                    let mut sink = [0u8; 4096];
                    let mut s = stream;
                    loop {
                        match s.read(&mut sink) {
                            Ok(0) => break,
                            Ok(_) => continue,
                            Err(_) => break,
                        }
                    }
                    let _ = s.shutdown(std::net::Shutdown::Write);
                }
                Ok(Value::Unit)
            }
            "touch_file" => {
                // touch_file(path) -> String message (OK <abs> or ERR: <msg>)
                let p = match args.get(0) { Some(Value::String(s)) => s.clone(), Some(v) => display_value(v), None => String::new() };
                if p.is_empty() { return Ok(Value::String("ERR: empty path".into())); }
                let path = std::path::Path::new(&p);
                if let Some(par) = path.parent() { let _ = std::fs::create_dir_all(par); }
                let res = std::fs::OpenOptions::new().create(true).write(true).truncate(true).open(&path);
                match res {
                    Ok(_) => {
                        let abs = std::fs::canonicalize(&path).unwrap_or_else(|_| path.to_path_buf());
                        Ok(Value::String(format!("OK {}", abs.display())))
                    }
                    Err(e) => Ok(Value::String(format!("ERR: {}", e)))
                }
            }
            "file_exists" => {
                // file_exists(path) -> "1" or "0"
                let p = match args.get(0) { Some(Value::String(s)) => s.clone(), Some(v) => display_value(v), None => String::new() };
                let exists = std::path::Path::new(&p).exists();
                Ok(Value::String(if exists { "1".into() } else { "0".into() }))
            }
            "infer_type_for" => {
                // args: pred, index, class
                if args.len() != 3 { return Ok(Value::Unit); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let idx = match &args[1] { Value::Number(n) => *n as usize, Value::String(s) => s.parse::<usize>().unwrap_or(0), _ => 0 };
                let class = match &args[2] { Value::String(s) => s.clone(), _ => String::new() };
                TYPE_RULES.with(|tr| { tr.borrow_mut().insert((pred, idx), class); });
                Ok(Value::Unit)
            }
            "fact" => {
                if args.len() != 3 { return Ok(Value::Unit); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let a = to_s(args.get(1).unwrap_or(&Value::Unit));
                let b = to_s(args.get(2).unwrap_or(&Value::Unit));
                FACTS.with(|f| {
                    let mut m = f.borrow_mut();
                    m.entry(pred).or_insert_with(Vec::new).push((a, b));
                });
                Ok(Value::Unit)
            }
            "goal" => {
                if args.is_empty() { return Ok(Value::Unit); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let mut items: Vec<String> = Vec::new();
                for a in &args[1..] { items.push(to_s(a)); }
                GOALS.with(|g| { g.borrow_mut().push((pred, items)); });
                Ok(Value::Unit)
            }
            "query" => {
                if args.len() != 3 { return Ok(Value::Number(0.0)); }
                let pred = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let a = to_s(args.get(1).unwrap_or(&Value::Unit));
                let mut count = 0usize;
                let mut bs: Vec<String> = Vec::new();
                FACTS.with(|f| {
                    if let Some(v) = f.borrow().get(&pred) {
                        for (x, b) in v.iter() {
                            if x == &a { count += 1; bs.push(b.clone()); }
                        }
                    }
                });
                // Apply simple type inference rules recorded
                TYPE_RULES.with(|tr| {
                    let rules = tr.borrow();
                    if let Some(class0) = rules.get(&(pred.clone(), 0usize)) { ensure_obj(&a, class0); }
                    if let Some(class1) = rules.get(&(pred.clone(), 1usize)) {
                        for b in bs.iter() { ensure_obj(b, class1); }
                    }
                });
                Ok(Value::Number(count as f64))
            }
            "new" => {
                if args.len() != 2 { return Ok(Value::Unit); }
                let class = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let name = match &args[1] { Value::String(s) => s.clone(), _ => String::new() };
                if !name.is_empty() { ensure_obj(&name, &class); }
                Ok(Value::String(name))
            }
            "set_var" => {
                if args.len() != 2 { return Ok(Value::Unit); }
                let key = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let val = args.get(1).cloned().unwrap_or(Value::Unit);
                if !key.is_empty() {
                    OBJECTS.with(|o| {
                        let mut b = o.borrow_mut();
                        let m = b.entry("__vars".to_string()).or_insert_with(HashMap::new);
                        m.insert(key, val);
                    });
                }
                Ok(Value::Unit)
            }
            "print" => {
                if let Some(x) = args.get(0) {
                    // Support simple string interpolation for IR runtime: "#{var}"
                    let s = display_value(x);
                    let out = interpolate(&s);
                    println!("{}", out);
                    // Flush so piped consumers (tests, process supervisors) see
                    // output promptly -- stdout is block-buffered when not a tty
                    use std::io::Write;
                    let _ = std::io::stdout().flush();
                }
                Ok(Value::Unit)
            },
            "sed" => {
                // sed("s/pat/repl/[flags]", input)
                let cmd = match args.get(0) { Some(Value::String(s)) => s.as_str(), _ => "" };
                let dv;
                let input: &str = match args.get(1) {
                    Some(Value::String(s)) => s.as_str(),
                    Some(v) => { dv = display_value(v); dv.as_str() },
                    None => "",
                };
                let out = sed_command(cmd, input);
                Ok(Value::String(out))
            },
            "add" => host_bin_num(args, |a,b| a+b),
            "multiply" => host_bin_num(args, |a,b| a*b),
            "subtract" => host_bin_num(args, |a,b| a-b),
            "max" => host_bin_num(args, |a,b| a.max(b)),
            "min" => host_bin_num(args, |a,b| a.min(b)),
            "calculate" => Ok(Value::Number(0.0)),
            "calculate_result" => Ok(Value::Number(0.0)),
            "get_value" => Ok(Value::Number(0.0)),
            "process" => Ok(Value::Bool(true)),
            "validate" => Ok(Value::Bool(true)),
            "len" => {
                let v = args.get(0).cloned().unwrap_or(Value::Unit);
                let n = match v {
                    Value::String(s) => s.chars().count() as f64,
                    Value::List(xs) => xs.len() as f64,
                    Value::Object(m) => m.len() as f64,
                    Value::Unit => 0.0,
                    _ => 0.0,
                };
                Ok(Value::Number(n))
            }
            "get" => {
                if args.len() != 2 { return Err("expected 2 args".into()); }
                let key = match &args[1] { Value::String(s) => s.clone(), _ => return Err("expected string key".into()) };
                match &args[0] {
                    Value::String(name) => Ok(obj_get(name, &key).unwrap_or(Value::Unit)),
                    Value::Object(map) => Ok(map.get(&key).cloned().unwrap_or(Value::Unit)),
                    _ => Ok(Value::Unit),
                }
            }
            "send" => {
                if args.len() < 2 { return Ok(Value::Unit); }
                let recv = match &args[0] { Value::String(s) => s.clone(), _ => String::new() };
                let method = match &args[1] { Value::String(s) => s.clone(), _ => String::new() };
                let rest = &args[2..];
                match method.as_str() {
                    "set" => {
                        if rest.len() != 2 { return Ok(Value::Unit); }
                        let prop = match &rest[0] { Value::String(s) => s.clone(), _ => String::new() };
                        let val = rest[1].clone();
                        if !recv.is_empty() && !prop.is_empty() { obj_set(&recv, &prop, val); }
                        Ok(Value::Unit)
                    }
                    "infer_is_adult" => {
                        // reads age, sets is_adult when >= 18
                        if let Some(Value::Number(age)) = obj_get(&recv, "age") {
                            if age >= 18.0 { obj_set(&recv, "is_adult", Value::Bool(true)); return Ok(Value::Bool(true)); }
                        } else if let Some(Value::String(s)) = obj_get(&recv, "age") {
                            if s.parse::<f64>().unwrap_or(0.0) >= 18.0 { obj_set(&recv, "is_adult", Value::Bool(true)); return Ok(Value::Bool(true)); }
                        }
                        Ok(Value::Bool(false))
                    }
                    "infer_relations" => {
                        // if exists fact("parent", X, recv) then set has_parent true
                        let mut has = false;
                        FACTS.with(|f| {
                            if let Some(v) = f.borrow().get("parent") {
                                has = v.iter().any(|(_, child)| child == &recv);
                            }
                        });
                        if has { obj_set(&recv, "has_parent", Value::Bool(true)); return Ok(Value::Bool(true)); }
                        Ok(Value::Bool(false))
                    }
                    _ => Ok(Value::Unit),
                }
            }
            other => Err(format!("host fn '{}' not found", other)),
        }
    }
}

fn host_bin_num(args: &[Value], f: fn(f64,f64)->f64) -> Result<Value, String> {
    let a = args.get(0).ok_or("expected 2 args")?;
    let b = args.get(1).ok_or("expected 2 args")?;
    let an = a.as_number()?; let bn = b.as_number()?;
    Ok(Value::Number(f(an,bn)))
}

fn display_value(v: &Value) -> String {
    match v {
        Value::Unit => String::new(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => if n.fract()==0.0 { format!("{}", *n as i64) } else { n.to_string() },
        Value::String(s) => s.clone(),
        Value::List(xs) => {
            let parts: Vec<String> = xs.iter().map(|x| display_value(x)).collect();
            format!("[{}]", parts.join(", "))
        }
        Value::Object(map) => {
            let mut kvs: Vec<String> = map.iter().map(|(k,v)| format!("{}: {}", k, display_value(v))).collect();
            kvs.sort();
            format!("{{{}}}", kvs.join(", "))
        }
        Value::Closure { .. } => "<closure>".into(),
    }
}

fn sed_command(cmd: &str, input: &str) -> String {
    if !cmd.starts_with('s') { return input.to_string(); }
    let mut parts = cmd.splitn(4, '/');
    let _s = parts.next();
    let pat = match parts.next() { Some(p) => p, None => return input.to_string() };
    let repl = match parts.next() { Some(r) => r, None => return input.to_string() };
    let flags = parts.next().unwrap_or("");
    let global = flags.contains('g');
    let ci = flags.contains('i');
    replace_lit(input, pat, repl, global, ci)
}

fn replace_lit(hay: &str, pat: &str, rep: &str, global: bool, ci: bool) -> String {
    if pat.is_empty() { return hay.to_string(); }
    if !ci {
        if !global {
            if let Some(pos) = hay.find(pat) {
                let mut out = String::with_capacity(hay.len());
                out.push_str(&hay[..pos]);
                out.push_str(rep);
                out.push_str(&hay[pos+pat.len()..]);
                return out;
            }
            return hay.to_string();
        } else {
            let mut out = String::with_capacity(hay.len());
            let mut start = 0usize;
            let mut rest = hay;
            while let Some(pos) = rest.find(pat) {
                let abs = start + pos;
                out.push_str(&hay[start..abs]);
                out.push_str(rep);
                start = abs + pat.len();
                rest = &hay[start..];
            }
            out.push_str(&hay[start..]);
            return out;
        }
    }
    let hay_l = hay.to_ascii_lowercase();
    let pat_l = pat.to_ascii_lowercase();
    if !global {
        if let Some(pos) = hay_l.find(&pat_l) {
            let mut out = String::with_capacity(hay.len());
            out.push_str(&hay[..pos]);
            out.push_str(rep);
            out.push_str(&hay[pos+pat.len()..]);
            return out;
        }
        return hay.to_string();
    } else {
        let mut out = String::with_capacity(hay.len());
        let mut start = 0usize;
        let mut idx = 0usize;
        while idx <= hay_l.len() {
            if let Some(pos) = hay_l[idx..].find(&pat_l) {
                let abs = idx + pos;
                out.push_str(&hay[start..abs]);
                out.push_str(rep);
                start = abs + pat.len();
                idx = start;
            } else { break; }
        }
        out.push_str(&hay[start..]);
        return out;
    }
}

// Simple interpolation: replace occurrences of #{name} using OBJECTS store vars or event locals if provided in scope.
fn interpolate(input: &str) -> String {
    let mut out = String::new();
    let b = input.as_bytes();
    let mut i = 0usize;
    while i < b.len() {
        if i + 2 < b.len() && b[i] as char == '#' && b[i+1] as char == '{' {
            i += 2; let start = i;
            while i < b.len() && b[i] as char != '}' { i += 1; }
            let key = &input[start..i];
            let val = resolve_interp_var(key);
            out.push_str(&val);
            if i < b.len() && b[i] as char == '}' { i += 1; }
        } else { out.push(b[i] as char); i += 1; }
    }
    out
}

fn resolve_interp_var(key: &str) -> String {
    // Try OBJECTS first (object.name property), then fall back to key itself.
    if let Some((obj, prop)) = key.split_once('.') {
        if let Some(v) = obj_get(obj, prop) { return display_value(&v); }
    } else {
        // No dot: may refer to a plain variable set on a synthetic "__vars" object by handlers.
        if let Some(v) = obj_get("__vars", key) { return display_value(&v); }
    }
    String::new()
}

#[derive(Clone)]
struct Function { name: String, params: Vec<String>, body: Vec<Instr> }

struct Program { functions: HashMap<String, Function>, entry: String }

fn run(program: &Program) -> Result<Value,String> {
    let entry = program.functions.get(&program.entry).ok_or("entry not found")?;
    run_function(program, entry, &[])
}

fn run_function(program: &Program, func: &Function, args: &[Value]) -> Result<Value,String> {
    let mut pc: usize = 0;
    let mut stack: Vec<Value> = Vec::new();
    let mut locals: HashMap<String, Value> = HashMap::new();
    // bind params
    for (i, p) in func.params.iter().enumerate() { if let Some(v) = args.get(i) { locals.insert(p.clone(), v.clone()); } }
    while pc < func.body.len() {
        match &func.body[pc] {
            Instr::Const(v) => stack.push(v.clone()),
            Instr::LoadLocal(n) => stack.push(locals.get(n).cloned().unwrap_or(Value::Unit)),
            Instr::StoreLocal(n) => { let v = stack.pop().ok_or("stack underflow")?; locals.insert(n.clone(), v); },
            Instr::UnOp(k) => {
                let a = stack.pop().ok_or("stack underflow")?;
                let r = match k { UnOpKind::Neg => Value::Number(-a.as_number()?), UnOpKind::Not => Value::Bool(!a.as_bool()?) };
                stack.push(r);
            }
            Instr::BinOp(k) => {
                use BinOpKind::*;
                let b = stack.pop().ok_or("stack underflow")?;
                let a = stack.pop().ok_or("stack underflow")?;
                let r = match k {
                    Add => add(&a,&b)?, Sub => sub(&a,&b)?, Mul => mul(&a,&b)?, Div => div(&a,&b)?, Mod => modu(&a,&b)?,
                    Eq|Ne|Lt|Le|Gt|Ge => cmp(k, &a, &b)?,
                    And => Value::Bool(a.as_bool()? && b.as_bool()?),
                    Or => Value::Bool(a.as_bool()? || b.as_bool()?),
                };
                stack.push(r);
            }
            Instr::Jump(t) => { pc = *t; continue; }
            Instr::JumpIfFalse(t) => { let c = stack.pop().ok_or("stack underflow")?; if !c.as_bool()? { pc = *t; continue; } }
            Instr::CallHost(n, argc) => {
                let argc = *argc; if stack.len() < argc { return Err("stack underflow".into()); }
                let args_index = stack.len() - argc; let args: Vec<Value> = stack.drain(args_index..).collect();
                if n == "emit" {
                    let ev = match args.get(0) { Some(Value::String(s)) => s.clone(), _ => String::new() };
                    let payload = args.get(1).cloned().unwrap_or(Value::Unit);
                    let mut last = Value::Unit;
                    let handlers: Vec<String> = EVENT_HANDLERS.with(|m| m.borrow().get(&ev).cloned().unwrap_or_default());
                    for h in handlers {
                        let callee = program.functions.get(&h).ok_or_else(|| format!("function '{}' not found", h))?;
                        // Expose event locals for interpolation via __vars as well
                        obj_set("__vars", "event_name", Value::String(ev.clone()));
                        obj_set("__vars", "event_data", payload.clone());
                        // Handlers are synthesized with parameters (event_name, event_data)
                        last = run_function(program, callee, &[Value::String(ev.clone()), payload.clone()])?;
                    }
                    stack.push(last);
                } else if n == "apply" {
                    // apply(fname, args...): call a program function by name
                    let fname = match args.get(0) {
                        Some(Value::String(s)) => s.clone(),
                        _ => return Err("apply: expected function name string".into()),
                    };
                    let callee = program.functions.get(&fname)
                        .ok_or_else(|| format!("apply: function '{}' not found", fname))?;
                    let r = run_function(program, callee, &args[1..])?;
                    stack.push(r);
                } else {
                    let r = Host::call(n, &args)?; stack.push(r);
                }
            }
            Instr::Call(n, argc) => {
                let argc = *argc; if stack.len() < argc { return Err("stack underflow".into()); }
                let args_index = stack.len() - argc; let args: Vec<Value> = stack.drain(args_index..).collect();
                let callee = program.functions.get(n).ok_or_else(|| format!("function '{}' not found", n))?;
                let r = run_function(program, callee, &args)?; stack.push(r);
            }
            Instr::MakeClosure(func_name, captured_names) => {
                let n = captured_names.len();
                if stack.len() < n { return Err("stack underflow".into()); }
                let start = stack.len() - n;
                let vals: Vec<Value> = stack.drain(start..).collect();
                let captured: Vec<(String, Value)> = captured_names.iter().cloned().zip(vals).collect();
                stack.push(Value::Closure { func_name: func_name.clone(), captured });
            }
            Instr::CallValue(argc) => {
                let argc = *argc; if stack.len() < argc { return Err("stack underflow".into()); }
                let args_index = stack.len() - argc;
                let call_args: Vec<Value> = stack.drain(args_index..).collect();
                let callee_val = stack.pop().ok_or("stack underflow")?;
                match callee_val {
                    Value::Closure { func_name, captured } => {
                        let mut full_args: Vec<Value> = captured.into_iter().map(|(_, v)| v).collect();
                        full_args.extend(call_args);
                        let callee = program.functions.get(&func_name).ok_or_else(|| format!("function '{}' not found", func_name))?;
                        let r = run_function(program, callee, &full_args)?;
                        stack.push(r);
                    }
                    other => return Err(format!("cannot call non-closure value: {:?}", other)),
                }
            }
            Instr::BuildList(n) => { let n=*n; if stack.len()<n {return Err("stack underflow".into());} let start=stack.len()-n; let items: Vec<Value>=stack.drain(start..).collect(); stack.push(Value::List(items)); }
            Instr::Return => { return Ok(stack.pop().unwrap_or(Value::Unit)); }
        }
        pc += 1;
    }
    Ok(stack.pop().unwrap_or(Value::Unit))
}

fn add(a:&Value,b:&Value)->Result<Value,String>{
    match (a,b) {
        (Value::String(sa), _) => Ok(Value::String(format!("{}{}", sa, to_s(b)))),
        (_, Value::String(sb)) => Ok(Value::String(format!("{}{}", to_s(a), sb))),
        _ => Ok(Value::Number(a.as_number()? + b.as_number()?)),
    }
}
fn sub(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? - b.as_number()?)) }
fn mul(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? * b.as_number()?)) }
fn div(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? / b.as_number()?)) }
fn modu(a:&Value,b:&Value)->Result<Value,String>{ Ok(Value::Number(a.as_number()? % b.as_number()?)) }
fn cmp(k:&BinOpKind,a:&Value,b:&Value)->Result<Value,String>{
    use BinOpKind::*;
    let res = match k {
        // Structural equality for Eq/Ne across all Value variants
        Eq => a == b,
        Ne => a != b,
        // Relational: lexicographic for string pairs, numeric otherwise
        Lt | Le | Gt | Ge => {
            if let (Value::String(x), Value::String(y)) = (a, b) {
                match k {
                    Lt => x < y,
                    Le => x <= y,
                    Gt => x > y,
                    Ge => x >= y,
                    _ => unreachable!(),
                }
            } else {
                let (an, bn) = (a.as_number()?, b.as_number()?);
                match k {
                    Lt => an < bn,
                    Le => an <= bn,
                    Gt => an > bn,
                    Ge => an >= bn,
                    _ => unreachable!(),
                }
            }
        }
        _ => false,
    };
    Ok(Value::Bool(res))
}
fn to_s(v:&Value)->String{ match v { Value::Unit=>String::new(), Value::Bool(b)=>b.to_string(), Value::Number(n)=> if n.fract()==0.0 {format!("{}",*n as i64)} else {n.to_string()}, Value::String(s)=>s.clone(), Value::List(xs)=>{ let parts:Vec<String>=xs.iter().map(|x|to_s(x)).collect(); format!("[{}]", parts.join(", ")) }, Value::Object(map)=>{ let mut kvs:Vec<String>=map.iter().map(|(k,v)| format!("{}: {}",k,to_s(v))).collect(); kvs.sort(); format!("{{{}}}", kvs.join(", ")) }, Value::Closure{..} => "<closure>".to_string() } }

fn main(){
    let program = build_program();
    match run(&program) { Ok(v) => println!("{}", display_value(&v)), Err(e) => { eprintln!("IR runtime error: {}", e); std::process::exit(1); } }
}

