Feature: sdsl_expand_trigger_blocks (self_hosting/lib/syntax_dsl.patlang, AUTO-PROBED)

  Background:
    This spec was generated by MECHANIZED probing, not hand-authored.
    It records ONE observed input/output example -- the first of a
    small bounded set of guessed literal values that ran without
    error, tried in an isolated subprocess. It is NOT a claim that
    this covers edge cases, error paths, or the function's full
    contract -- only that this exact call, with this exact input,
    produced this exact output, with no error, at the time this was
    generated.

  Scenario: One example call succeeds
    Given 2 argument(s), each the literal "test"
    When sdsl_expand_trigger_blocks is called
    Then it returns without error (see the recorded output in this spec's own .meta.json)

